
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "S107:Methods should not have too many parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ShipWorks.Shipping.Tests.Integration.Services.InsuranceViewModelTest.Express1Endicia_ValuesMatch_Test(System.Decimal,ShipWorks.Shipping.Insurance.InsuranceProvider,System.Boolean,System.Windows.Visibility,System.Windows.Visibility,System.Windows.Visibility,System.String,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "S107:Methods should not have too many parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ShipWorks.Shipping.Tests.Integration.Services.InsuranceViewModelTest.OnTrac_ValuesMatch_Test(System.Decimal,System.Boolean,ShipWorks.Shipping.Insurance.InsuranceProvider,System.Boolean,System.Windows.Visibility,System.Windows.Visibility,System.Windows.Visibility,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "S107:Methods should not have too many parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ShipWorks.Shipping.Tests.Integration.Services.InsuranceViewModelTest.Endicia_ValuesMatch_Test(System.Decimal,ShipWorks.Shipping.Insurance.InsuranceProvider,System.Boolean,System.Windows.Visibility,System.Windows.Visibility,System.Windows.Visibility,System.String,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "S107:Methods should not have too many parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ShipWorks.Shipping.Tests.Integration.Services.InsuranceViewModelTest.Express1Usps_ValuesMatch_Test(System.Decimal,ShipWorks.Shipping.Insurance.InsuranceProvider,System.Boolean,System.Windows.Visibility,System.Windows.Visibility,System.Windows.Visibility,System.String,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "S107:Methods should not have too many parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ShipWorks.Shipping.Tests.Integration.Services.InsuranceViewModelTest.None_ValuesMatch_Test(System.Decimal,ShipWorks.Shipping.Insurance.InsuranceProvider,System.Boolean,System.Windows.Visibility,System.Windows.Visibility,System.Windows.Visibility,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "S107:Methods should not have too many parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ShipWorks.Shipping.Tests.Integration.Services.InsuranceViewModelTest.Other_ValuesMatch(System.Decimal,ShipWorks.Shipping.Insurance.InsuranceProvider,System.Boolean,System.Windows.Visibility,System.Windows.Visibility,System.Windows.Visibility,System.String,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "S107:Methods should not have too many parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ShipWorks.Shipping.Tests.Integration.Services.InsuranceViewModelTest.Other_ValuesMatch_Test(System.Decimal,ShipWorks.Shipping.Insurance.InsuranceProvider,System.Boolean,System.Windows.Visibility,System.Windows.Visibility,System.Windows.Visibility,System.String,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "S107:Methods should not have too many parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ShipWorks.Shipping.Tests.Integration.Services.InsuranceViewModelTest.Postal_ValuesMatch(ShipWorks.Shipping.ShipmentTypeCode,System.Decimal,ShipWorks.Shipping.Insurance.InsuranceProvider,System.Boolean,System.Windows.Visibility,System.Windows.Visibility,System.Windows.Visibility,System.String,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "S107:Methods should not have too many parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ShipWorks.Shipping.Tests.Integration.Services.InsuranceViewModelTest.PostalWebTools_ValuesMatch_Test(System.Decimal,ShipWorks.Shipping.Insurance.InsuranceProvider,System.Boolean,System.Windows.Visibility,System.Windows.Visibility,System.Windows.Visibility,System.String,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "S107:Methods should not have too many parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ShipWorks.Shipping.Tests.Integration.Services.InsuranceViewModelTest.Usps_ValuesMatch_Test(System.Decimal,ShipWorks.Shipping.Insurance.InsuranceProvider,System.Boolean,System.Windows.Visibility,System.Windows.Visibility,System.Windows.Visibility,System.String,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "S107:Methods should not have too many parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ShipWorks.Shipping.Tests.Integration.Services.InsuranceViewModelTest.FedEx_ValuesMatch_Test(System.Decimal,System.Boolean,ShipWorks.Shipping.Insurance.InsuranceProvider,System.Boolean,System.Windows.Visibility,System.Windows.Visibility,System.Windows.Visibility,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "S107:Methods should not have too many parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ShipWorks.Shipping.Tests.Integration.Services.InsuranceViewModelTest.IParcel_ValuesMatch_Test(System.Decimal,System.Boolean,ShipWorks.Shipping.Insurance.InsuranceProvider,System.Boolean,System.Windows.Visibility,System.Windows.Visibility,System.Windows.Visibility,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintainability", "S107:Methods should not have too many parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ShipWorks.Shipping.Tests.Integration.Services.InsuranceViewModelTest.Ups_ValuesMatch_Test(System.Decimal,System.Boolean,ShipWorks.Shipping.Insurance.InsuranceProvider,System.Boolean,System.Windows.Visibility,System.Windows.Visibility,System.Windows.Visibility,System.String,System.String)")]