[{
    "id": 100,
    "customer_id": 1,
    "date_created": "Thu, 20 Apr 2017 19:45:47 +0000",
    "date_modified": "Mon, 24 Apr 2017 11:47:00 +0000",
    "date_shipped": "",
    "status_id": 1,
    "status": "Pending",
    "subtotal_ex_tax": "10.0000",
    "subtotal_inc_tax": "10.0000",
    "subtotal_tax": "0.0000",
    "base_shipping_cost": "0.0000",
    "shipping_cost_ex_tax": "0.0000",
    "shipping_cost_inc_tax": "0.0000",
    "shipping_cost_tax": "0.0000",
    "shipping_cost_tax_class_id": 2,
    "base_handling_cost": "0.0000",
    "handling_cost_ex_tax": "0.0000",
    "handling_cost_inc_tax": "0.0000",
    "handling_cost_tax": "0.0000",
    "handling_cost_tax_class_id": 2,
    "base_wrapping_cost": "0.0000",
    "wrapping_cost_ex_tax": "0.0000",
    "wrapping_cost_inc_tax": "0.0000",
    "wrapping_cost_tax": "0.0000",
    "wrapping_cost_tax_class_id": 3,
    "total_ex_tax": "10.0000",
    "total_inc_tax": "10.0000",
    "total_tax": "0.0000",
    "items_total": 1,
    "items_shipped": 0,
    "payment_method": "1",
    "payment_provider_id": null,
    "payment_status": "",
    "refunded_amount": "0.0000",
    "order_is_digital": false,
    "store_credit_amount": "0.0000",
    "gift_certificate_amount": "0.0000",
    "ip_address": "66.128.118.226",
    "geoip_country": "United States",
    "geoip_country_iso2": "US",
    "currency_id": 1,
    "currency_code": "USD",
    "currency_exchange_rate": "1.0000000000",
    "default_currency_id": 1,
    "default_currency_code": "USD",
    "staff_notes": "",
    "customer_message": "",
    "discount_amount": "0.0000",
    "coupon_discount": "0.0000",
    "shipping_address_count": 1,
    "is_deleted": false,
    "ebay_order_id": "0",
    "billing_address": {
        "first_name": "John",
        "last_name": "Doe",
        "company": "StoreWithNotes",
        "street_1": "1 s memorial drive",
        "street_2": "",
        "city": "Saint LOUis",
        "state": "Missouri",
        "zip": "63102",
        "country": "United States",
        "country_iso2": "US",
        "phone": "",
        "email": "me@me.com",
        "form_fields": []
    },
    "is_email_opt_in": false,
    "credit_card_type": null,
    "order_source": "manual",
    "external_source": null,
    "products": {
        "url": "https://api.bigcommerce.com/stores/vplh1lw/v2/orders/100/products",
        "resource": "/orders/100/products"
    },
    "shipping_addresses": {
        "url": "https://api.bigcommerce.com/stores/vplh1lw/v2/orders/100/shippingaddresses",
        "resource": "/orders/100/shippingaddresses"
    },
    "coupons": {
        "url": "https://api.bigcommerce.com/stores/vplh1lw/v2/orders/100/coupons",
        "resource": "/orders/100/coupons"
    },
    "external_id": null
}]
