[{
    "id": 1,
    "order_id": 100,
    "first_name": "John",
    "last_name": "Doe",
    "company": "StoreWithNotes",
    "street_1": "1 s memorial drive",
    "street_2": "",
    "city": "Saint LOUis",
    "zip": "63102",
    "country": "United States",
    "country_iso2": "US",
    "state": "Missouri",
    "email": "me@me.com",
    "phone": "",
    "items_total": 1,
    "items_shipped": 0,
    "shipping_method": "None",
    "base_cost": "0.0000",
    "cost_ex_tax": "0.0000",
    "cost_inc_tax": "0.0000",
    "cost_tax": "0.0000",
    "cost_tax_class_id": 2,
    "base_handling_cost": "0.0000",
    "handling_cost_ex_tax": "0.0000",
    "handling_cost_inc_tax": "0.0000",
    "handling_cost_tax": "0.0000",
    "handling_cost_tax_class_id": 2,
    "shipping_zone_id": 1,
    "shipping_zone_name": "United States",
    "form_fields": []
}]
