///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SmokeTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The EnableUPSMailInnovations recording.
    /// </summary>
    [TestModule("bd4418eb-6900-4b58-8694-2ab3473ead47", ModuleType.Recording, 1)]
    public partial class EnableUPSMailInnovations : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SmokeTestRepository repository.
        /// </summary>
        public static SmokeTestRepository repo = SmokeTestRepository.Instance;

        static EnableUPSMailInnovations instance = new EnableUPSMailInnovations();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public EnableUPSMailInnovations()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static EnableUPSMailInnovations Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 1000;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'ShipWorksSa.Home1' at Center.", repo.ShipWorksSa.Home1Info, new RecordItemIndex(0));
            repo.ShipWorksSa.Home1.MoveTo();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShipWorksSa.Home1' at Center.", repo.ShipWorksSa.Home1Info, new RecordItemIndex(1));
            repo.ShipWorksSa.Home1.Click();
            Delay.Milliseconds(0);
            
            // Mouse Move to avoid click inconsistency
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Move to avoid click inconsistency\r\nMouse Left Move item 'MainForm.Manage' at Center.", repo.MainForm.ManageInfo, new RecordItemIndex(2));
            repo.MainForm.Manage.MoveTo(300);
            Delay.Milliseconds(200);
            
            // Click: Manage ribbon buttons
            Report.Log(ReportLevel.Info, "Mouse", "Click: Manage ribbon buttons\r\nMouse Left Click item 'MainForm.Manage' at Center.", repo.MainForm.ManageInfo, new RecordItemIndex(3));
            repo.MainForm.Manage.Click(300);
            Delay.Milliseconds(200);
            
            // Mouse Move to avoid click inconsistency
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Move to avoid click inconsistency\r\nMouse Left Move item 'MainForm.Shipping' at Center.", repo.MainForm.ShippingInfo, new RecordItemIndex(4));
            repo.MainForm.Shipping.MoveTo(300);
            Delay.Milliseconds(200);
            
            // Click: Shipping Settings button
            Report.Log(ReportLevel.Info, "Mouse", "Click: Shipping Settings button\r\nMouse Left Click item 'MainForm.Shipping' at Center.", repo.MainForm.ShippingInfo, new RecordItemIndex(5));
            repo.MainForm.Shipping.Click(300);
            Delay.Milliseconds(200);
            
            // Mouse Move to avoid click inconsistency
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Move to avoid click inconsistency\r\nMouse Left Move item 'ShippingSettingsDlg.ListItemUPS' at Center.", repo.ShippingSettingsDlg.ListItemUPSInfo, new RecordItemIndex(6));
            repo.ShippingSettingsDlg.ListItemUPS.MoveTo(300);
            Delay.Milliseconds(200);
            
            // Click: UPS (Provider)
            Report.Log(ReportLevel.Info, "Mouse", "Click: UPS (Provider)\r\nMouse Left Click item 'ShippingSettingsDlg.ListItemUPS' at Center.", repo.ShippingSettingsDlg.ListItemUPSInfo, new RecordItemIndex(7));
            repo.ShippingSettingsDlg.ListItemUPS.Click(300);
            Delay.Milliseconds(200);
            
            // Give Focus
            Report.Log(ReportLevel.Info, "Invoke action", "Give Focus\r\nInvoking Focus() on item 'ShippingSettingsDlg.TabPageSettings.MailInnovations'.", repo.ShippingSettingsDlg.TabPageSettings.MailInnovationsInfo, new RecordItemIndex(8));
            repo.ShippingSettingsDlg.TabPageSettings.MailInnovations.Focus();
            Delay.Milliseconds(0);
            
            // Mouse Move to avoid click inconsistency
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Move to avoid click inconsistency\r\nMouse Left Move item 'ShippingSettingsDlg.TabPageSettings.MailInnovations' at Center.", repo.ShippingSettingsDlg.TabPageSettings.MailInnovationsInfo, new RecordItemIndex(9));
            repo.ShippingSettingsDlg.TabPageSettings.MailInnovations.MoveTo(300);
            Delay.Milliseconds(200);
            
            // Set Checked: UPS Mail Innovations checkbox
            Report.Log(ReportLevel.Info, "Set value", "Set Checked: UPS Mail Innovations checkbox\r\nSetting attribute Checked to 'true' on item 'ShippingSettingsDlg.TabPageSettings.MailInnovations'.", repo.ShippingSettingsDlg.TabPageSettings.MailInnovationsInfo, new RecordItemIndex(10));
            repo.ShippingSettingsDlg.TabPageSettings.MailInnovations.Element.SetAttributeValue("Checked", "true");
            Delay.Milliseconds(0);
            
            // Mouse Move to avoid click inconsistency
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Move to avoid click inconsistency\r\nMouse Left Move item 'ShippingSettingsDlg.Close' at Center.", repo.ShippingSettingsDlg.CloseInfo, new RecordItemIndex(11));
            repo.ShippingSettingsDlg.Close.MoveTo(300);
            Delay.Milliseconds(200);
            
            // Click: Close
            Report.Log(ReportLevel.Info, "Mouse", "Click: Close\r\nMouse Left Click item 'ShippingSettingsDlg.Close' at Center.", repo.ShippingSettingsDlg.CloseInfo, new RecordItemIndex(12));
            repo.ShippingSettingsDlg.Close.Click(300);
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
