///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SmokeTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SwitchBatchGridToOrderLookup recording.
    /// </summary>
    [TestModule("9edd78a8-1b4b-4035-af81-d5ac4f2f0ab9", ModuleType.Recording, 1)]
    public partial class SwitchBatchGridToOrderLookup : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SmokeTestRepository repository.
        /// </summary>
        public static SmokeTestRepository repo = SmokeTestRepository.Instance;

        static SwitchBatchGridToOrderLookup instance = new SwitchBatchGridToOrderLookup();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SwitchBatchGridToOrderLookup()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SwitchBatchGridToOrderLookup Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // Validates ShipWorks is in Batch Grid
            Report.Log(ReportLevel.Info, "Validation", "Validates ShipWorks is in Batch Grid\r\nValidating AttributeEqual (ControlText='All') on item 'ShipWorksSa.PanelDockingArea.KryptonHeader'.", repo.ShipWorksSa.PanelDockingArea.KryptonHeaderInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.ShipWorksSa.PanelDockingArea.KryptonHeaderInfo, "ControlText", "All");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'ShipWorksSa.Application' at Center.", repo.ShipWorksSa.ApplicationInfo, new RecordItemIndex(1));
            repo.ShipWorksSa.Application.MoveTo();
            Delay.Milliseconds(200);
            
            // Clicks ShipWorks Logo
            Report.Log(ReportLevel.Info, "Mouse", "Clicks ShipWorks Logo\r\nMouse Left Click item 'ShipWorksSa.Application' at Center.", repo.ShipWorksSa.ApplicationInfo, new RecordItemIndex(2));
            repo.ShipWorksSa.Application.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShipWorks.ViewMode' at Center.", repo.ShipWorks.ViewModeInfo, new RecordItemIndex(3));
            repo.ShipWorks.ViewMode.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(4));
            Delay.Duration(3000, false);
            
            // Selects Order Lookup Mode
            Report.Log(ReportLevel.Info, "Keyboard", "Selects Order Lookup Mode\r\nKey sequence 'O'.", new RecordItemIndex(5));
            Keyboard.Press("O");
            Delay.Milliseconds(0);
            
            // Validates ShipWorks is in Order Lookup
            Report.Log(ReportLevel.Info, "Validation", "Validates ShipWorks is in Order Lookup\r\nValidating AttributeEqual (Text='Order Number') on item 'ShipWorksSa.PanelDockingArea.OrderNumber'.", repo.ShipWorksSa.PanelDockingArea.OrderNumberInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.ShipWorksSa.PanelDockingArea.OrderNumberInfo, "Text", "Order Number");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
