///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ShippingCarrierRegression
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ProcessUPSExtreme recording.
    /// </summary>
    [TestModule("7cb3f17e-d0d4-4539-b01c-21aa50ac628b", ModuleType.Recording, 1)]
    public partial class ProcessUPSExtreme : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ShippingCarrierRegressionRepository repository.
        /// </summary>
        public static ShippingCarrierRegressionRepository repo = ShippingCarrierRegressionRepository.Instance;

        static ProcessUPSExtreme instance = new ProcessUPSExtreme();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ProcessUPSExtreme()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ProcessUPSExtreme Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            // Focus on the Service Dropdown
            Report.Log(ReportLevel.Info, "Invoke Action", "Focus on the Service Dropdown\r\nInvoking Focus() on item 'ShippingDlg.SplitContainer.Service'.", repo.ShippingDlg.SplitContainer.ServiceInfo, new RecordItemIndex(0));
            repo.ShippingDlg.SplitContainer.Service.Focus();
            
            // Move to the Service Dropdown
            Report.Log(ReportLevel.Info, "Mouse", "Move to the Service Dropdown\r\nMouse Left Move item 'ShippingDlg.SplitContainer.Service' at Center.", repo.ShippingDlg.SplitContainer.ServiceInfo, new RecordItemIndex(1));
            repo.ShippingDlg.SplitContainer.Service.MoveTo();
            
            // Click the service dropdown
            Report.Log(ReportLevel.Info, "Mouse", "Click the service dropdown\r\nMouse Left Click item 'ShippingDlg.SplitContainer.Service' at Center.", repo.ShippingDlg.SplitContainer.ServiceInfo, new RecordItemIndex(2));
            repo.ShippingDlg.SplitContainer.Service.Click();
            
            // Select UPS Ground in the service dropdown
            Report.Log(ReportLevel.Info, "Set Value", "Select UPS Ground in the service dropdown\r\nSetting attribute SelectedItemText to 'UPS Ground' on item 'ShippingDlg.SplitContainer.Service'.", repo.ShippingDlg.SplitContainer.ServiceInfo, new RecordItemIndex(3));
            repo.ShippingDlg.SplitContainer.Service.Element.SetAttributeValue("SelectedItemText", "UPS Ground");
            
            // Focus on the Weight field
            Report.Log(ReportLevel.Info, "Invoke Action", "Focus on the Weight field\r\nInvoking Focus() on item 'ShippingDlg.SplitContainer.UPSWeight'.", repo.ShippingDlg.SplitContainer.UPSWeightInfo, new RecordItemIndex(4));
            repo.ShippingDlg.SplitContainer.UPSWeight.Focus();
            
            // Move to the Weight field
            Report.Log(ReportLevel.Info, "Mouse", "Move to the Weight field\r\nMouse Left Move item 'ShippingDlg.SplitContainer.UPSWeight' at Center.", repo.ShippingDlg.SplitContainer.UPSWeightInfo, new RecordItemIndex(5));
            repo.ShippingDlg.SplitContainer.UPSWeight.MoveTo();
            
            // Select all text in the Weight field
            Report.Log(ReportLevel.Info, "Keyboard", "Select all text in the Weight field\r\nKey 'Ctrl+A' Press with focus on 'ShippingDlg.SplitContainer.UPSWeight'.", repo.ShippingDlg.SplitContainer.UPSWeightInfo, new RecordItemIndex(6));
            Keyboard.PrepareFocus(repo.ShippingDlg.SplitContainer.UPSWeight);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            
            // Enter "5" in the Weight field
            Report.Log(ReportLevel.Info, "Keyboard", "Enter \"5\" in the Weight field\r\nKey sequence '5' with focus on 'ShippingDlg.SplitContainer.UPSWeight'.", repo.ShippingDlg.SplitContainer.UPSWeightInfo, new RecordItemIndex(7));
            repo.ShippingDlg.SplitContainer.UPSWeight.PressKeys("5");
            
            // Focus on the Length field
            Report.Log(ReportLevel.Info, "Invoke Action", "Focus on the Length field\r\nInvoking Focus() on item 'ShippingDlg.DimensionsControl.Lengthiparcel'.", repo.ShippingDlg.DimensionsControl.LengthiparcelInfo, new RecordItemIndex(8));
            repo.ShippingDlg.DimensionsControl.Lengthiparcel.Focus();
            
            // Move to the Length field
            Report.Log(ReportLevel.Info, "Mouse", "Move to the Length field\r\nMouse Left Move item 'ShippingDlg.DimensionsControl.Lengthiparcel' at Center.", repo.ShippingDlg.DimensionsControl.LengthiparcelInfo, new RecordItemIndex(9));
            repo.ShippingDlg.DimensionsControl.Lengthiparcel.MoveTo();
            
            // Select all text in the Length field
            Report.Log(ReportLevel.Info, "Keyboard", "Select all text in the Length field\r\nKey 'Ctrl+A' Press with focus on 'ShippingDlg.DimensionsControl.Lengthiparcel'.", repo.ShippingDlg.DimensionsControl.LengthiparcelInfo, new RecordItemIndex(10));
            Keyboard.PrepareFocus(repo.ShippingDlg.DimensionsControl.Lengthiparcel);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            
            // Enter 33 in the Length field
            Report.Log(ReportLevel.Info, "Keyboard", "Enter 33 in the Length field\r\nKey sequence '33' with focus on 'ShippingDlg.DimensionsControl.Lengthiparcel'.", repo.ShippingDlg.DimensionsControl.LengthiparcelInfo, new RecordItemIndex(11));
            repo.ShippingDlg.DimensionsControl.Lengthiparcel.PressKeys("33");
            
            // Focus on the Width field
            Report.Log(ReportLevel.Info, "Invoke Action", "Focus on the Width field\r\nInvoking Focus() on item 'ShippingDlg.DimensionsControl.Widthiparcel'.", repo.ShippingDlg.DimensionsControl.WidthiparcelInfo, new RecordItemIndex(12));
            repo.ShippingDlg.DimensionsControl.Widthiparcel.Focus();
            
            // Move to the Width field
            Report.Log(ReportLevel.Info, "Mouse", "Move to the Width field\r\nMouse Left Move item 'ShippingDlg.DimensionsControl.Widthiparcel' at Center.", repo.ShippingDlg.DimensionsControl.WidthiparcelInfo, new RecordItemIndex(13));
            repo.ShippingDlg.DimensionsControl.Widthiparcel.MoveTo();
            
            // Select all text in the Width field
            Report.Log(ReportLevel.Info, "Keyboard", "Select all text in the Width field\r\nKey 'Ctrl+A' Press with focus on 'ShippingDlg.DimensionsControl.Widthiparcel'.", repo.ShippingDlg.DimensionsControl.WidthiparcelInfo, new RecordItemIndex(14));
            Keyboard.PrepareFocus(repo.ShippingDlg.DimensionsControl.Widthiparcel);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            
            // Enter 33 in the Width field
            Report.Log(ReportLevel.Info, "Keyboard", "Enter 33 in the Width field\r\nKey sequence '33' with focus on 'ShippingDlg.DimensionsControl.Widthiparcel'.", repo.ShippingDlg.DimensionsControl.WidthiparcelInfo, new RecordItemIndex(15));
            repo.ShippingDlg.DimensionsControl.Widthiparcel.PressKeys("33");
            
            // Focus on the Height field
            Report.Log(ReportLevel.Info, "Invoke Action", "Focus on the Height field\r\nInvoking Focus() on item 'ShippingDlg.DimensionsControl.Heightiparcel'.", repo.ShippingDlg.DimensionsControl.HeightiparcelInfo, new RecordItemIndex(16));
            repo.ShippingDlg.DimensionsControl.Heightiparcel.Focus();
            
            // Move to the Height field
            Report.Log(ReportLevel.Info, "Mouse", "Move to the Height field\r\nMouse Left Move item 'ShippingDlg.DimensionsControl.Heightiparcel' at 29;10.", repo.ShippingDlg.DimensionsControl.HeightiparcelInfo, new RecordItemIndex(17));
            repo.ShippingDlg.DimensionsControl.Heightiparcel.MoveTo("29;10");
            
            // Select all in the Height field
            Report.Log(ReportLevel.Info, "Keyboard", "Select all in the Height field\r\nKey sequence '{LControlKey down}{Akey}{LControlKey up}' with focus on 'ShippingDlg.DimensionsControl.Heightiparcel'.", repo.ShippingDlg.DimensionsControl.HeightiparcelInfo, new RecordItemIndex(18));
            repo.ShippingDlg.DimensionsControl.Heightiparcel.PressKeys("{LControlKey down}{Akey}{LControlKey up}");
            
            // Enter 33 in the Height field
            Report.Log(ReportLevel.Info, "Keyboard", "Enter 33 in the Height field\r\nKey sequence '33' with focus on 'ShippingDlg.DimensionsControl.Heightiparcel'.", repo.ShippingDlg.DimensionsControl.HeightiparcelInfo, new RecordItemIndex(19));
            repo.ShippingDlg.DimensionsControl.Heightiparcel.PressKeys("33");
            
            // Verify that UPS Ground shows up in the rate section of the Ship Order UI
            Report.Log(ReportLevel.Info, "Validation", "Verify that UPS Ground shows up in the rate section of the Ship Order UI\r\nValidating AttributeEqual (RawText='UPS Ground') on item 'ShippingDlg.SplitContainer.UPSGround1'.", repo.ShippingDlg.SplitContainer.UPSGround1Info, new RecordItemIndex(20));
            Validate.Attribute(repo.ShippingDlg.SplitContainer.UPSGround1Info, "RawText", "UPS Ground");
            
            // Focus on the Height field
            Report.Log(ReportLevel.Info, "Invoke Action", "Focus on the Height field\r\nInvoking Focus() on item 'ShippingDlg.DimensionsControl.Heightiparcel'.", repo.ShippingDlg.DimensionsControl.HeightiparcelInfo, new RecordItemIndex(21));
            repo.ShippingDlg.DimensionsControl.Heightiparcel.Focus();
            
            // Move to the Height field
            Report.Log(ReportLevel.Info, "Mouse", "Move to the Height field\r\nMouse Left Move item 'ShippingDlg.DimensionsControl.Heightiparcel' at Center.", repo.ShippingDlg.DimensionsControl.HeightiparcelInfo, new RecordItemIndex(22));
            repo.ShippingDlg.DimensionsControl.Heightiparcel.MoveTo();
            
            // Select all in the Height field
            Report.Log(ReportLevel.Info, "Keyboard", "Select all in the Height field\r\nKey 'Ctrl+A' Press with focus on 'ShippingDlg.DimensionsControl.Heightiparcel'.", repo.ShippingDlg.DimensionsControl.HeightiparcelInfo, new RecordItemIndex(23));
            Keyboard.PrepareFocus(repo.ShippingDlg.DimensionsControl.Heightiparcel);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            
            // Enter 34 in the Height field
            Report.Log(ReportLevel.Info, "Keyboard", "Enter 34 in the Height field\r\nKey sequence '34' with focus on 'ShippingDlg.DimensionsControl.Heightiparcel'.", repo.ShippingDlg.DimensionsControl.HeightiparcelInfo, new RecordItemIndex(24));
            repo.ShippingDlg.DimensionsControl.Heightiparcel.PressKeys("34");
            
            // Click the Rate grid
            Report.Log(ReportLevel.Info, "Mouse", "Click the Rate grid\r\nMouse Left Click item 'ShippingDlg.SplitContainer.RateGrid' at Center.", repo.ShippingDlg.SplitContainer.RateGridInfo, new RecordItemIndex(25));
            repo.ShippingDlg.SplitContainer.RateGrid.Click();
            
            // Verify that the correct error footer shows up
            Report.Log(ReportLevel.Info, "Validation", "Verify that the correct error footer shows up\r\nValidating AttributeEqual (RawText='Some errors occurred while getting rates.') on item 'ShippingDlg.SplitContainer.SomeErrorsOccurredWhileGettingRates'.", repo.ShippingDlg.SplitContainer.SomeErrorsOccurredWhileGettingRatesInfo, new RecordItemIndex(26));
            Validate.Attribute(repo.ShippingDlg.SplitContainer.SomeErrorsOccurredWhileGettingRatesInfo, "RawText", "Some errors occurred while getting rates.");
            
            // Focus on the Height field
            Report.Log(ReportLevel.Info, "Invoke Action", "Focus on the Height field\r\nInvoking Focus() on item 'ShippingDlg.DimensionsControl.Heightiparcel'.", repo.ShippingDlg.DimensionsControl.HeightiparcelInfo, new RecordItemIndex(27));
            repo.ShippingDlg.DimensionsControl.Heightiparcel.Focus();
            
            // Move to the Height field
            Report.Log(ReportLevel.Info, "Mouse", "Move to the Height field\r\nMouse Left Move item 'ShippingDlg.DimensionsControl.Heightiparcel' at Center.", repo.ShippingDlg.DimensionsControl.HeightiparcelInfo, new RecordItemIndex(28));
            repo.ShippingDlg.DimensionsControl.Heightiparcel.MoveTo();
            
            // Select all in the Height field
            Report.Log(ReportLevel.Info, "Keyboard", "Select all in the Height field\r\nKey 'Ctrl+A' Press with focus on 'ShippingDlg.DimensionsControl.Heightiparcel'.", repo.ShippingDlg.DimensionsControl.HeightiparcelInfo, new RecordItemIndex(29));
            Keyboard.PrepareFocus(repo.ShippingDlg.DimensionsControl.Heightiparcel);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            
            // Enter 33 in the Height field
            Report.Log(ReportLevel.Info, "Keyboard", "Enter 33 in the Height field\r\nKey sequence '33' with focus on 'ShippingDlg.DimensionsControl.Heightiparcel'.", repo.ShippingDlg.DimensionsControl.HeightiparcelInfo, new RecordItemIndex(30));
            repo.ShippingDlg.DimensionsControl.Heightiparcel.PressKeys("33");
            
            // Focus to the Weight field
            Report.Log(ReportLevel.Info, "Invoke Action", "Focus to the Weight field\r\nInvoking Focus() on item 'ShippingDlg.SplitContainer.UPSWeight'.", repo.ShippingDlg.SplitContainer.UPSWeightInfo, new RecordItemIndex(31));
            repo.ShippingDlg.SplitContainer.UPSWeight.Focus();
            
            // Move to the Weight field
            Report.Log(ReportLevel.Info, "Mouse", "Move to the Weight field\r\nMouse Left Move item 'ShippingDlg.SplitContainer.UPSWeight' at Center.", repo.ShippingDlg.SplitContainer.UPSWeightInfo, new RecordItemIndex(32));
            repo.ShippingDlg.SplitContainer.UPSWeight.MoveTo();
            
            // Select all text in the Weight field
            Report.Log(ReportLevel.Info, "Keyboard", "Select all text in the Weight field\r\nKey 'Ctrl+A' Press with focus on 'ShippingDlg.SplitContainer.UPSWeight'.", repo.ShippingDlg.SplitContainer.UPSWeightInfo, new RecordItemIndex(33));
            Keyboard.PrepareFocus(repo.ShippingDlg.SplitContainer.UPSWeight);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            
            // Enter "150" in the Weight field
            Report.Log(ReportLevel.Info, "Keyboard", "Enter \"150\" in the Weight field\r\nKey sequence '150' with focus on 'ShippingDlg.SplitContainer.UPSWeight'.", repo.ShippingDlg.SplitContainer.UPSWeightInfo, new RecordItemIndex(34));
            repo.ShippingDlg.SplitContainer.UPSWeight.PressKeys("150");
            
            // Verify that UPS Ground shows up in the rates area of the Ship Orders UI
            Report.Log(ReportLevel.Info, "Validation", "Verify that UPS Ground shows up in the rates area of the Ship Orders UI\r\nValidating AttributeEqual (RawText='UPS Ground') on item 'ShippingDlg.SplitContainer.UPSGround1'.", repo.ShippingDlg.SplitContainer.UPSGround1Info, new RecordItemIndex(35));
            Validate.Attribute(repo.ShippingDlg.SplitContainer.UPSGround1Info, "RawText", "UPS Ground");
            
            // Focus to the Weight field
            Report.Log(ReportLevel.Info, "Invoke Action", "Focus to the Weight field\r\nInvoking Focus() on item 'ShippingDlg.SplitContainer.UPSWeight'.", repo.ShippingDlg.SplitContainer.UPSWeightInfo, new RecordItemIndex(36));
            repo.ShippingDlg.SplitContainer.UPSWeight.Focus();
            
            // Move to the Weight field
            Report.Log(ReportLevel.Info, "Mouse", "Move to the Weight field\r\nMouse Left Move item 'ShippingDlg.SplitContainer.UPSWeight' at Center.", repo.ShippingDlg.SplitContainer.UPSWeightInfo, new RecordItemIndex(37));
            repo.ShippingDlg.SplitContainer.UPSWeight.MoveTo();
            
            // Select all text in the Weight field
            Report.Log(ReportLevel.Info, "Keyboard", "Select all text in the Weight field\r\nKey 'Ctrl+A' Press with focus on 'ShippingDlg.SplitContainer.UPSWeight'.", repo.ShippingDlg.SplitContainer.UPSWeightInfo, new RecordItemIndex(38));
            Keyboard.PrepareFocus(repo.ShippingDlg.SplitContainer.UPSWeight);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            
            // Enter "151" in the Weight field
            Report.Log(ReportLevel.Info, "Keyboard", "Enter \"151\" in the Weight field\r\nKey sequence '151' with focus on 'ShippingDlg.SplitContainer.UPSWeight'.", repo.ShippingDlg.SplitContainer.UPSWeightInfo, new RecordItemIndex(39));
            repo.ShippingDlg.SplitContainer.UPSWeight.PressKeys("151");
            
            // Click the rate grid
            Report.Log(ReportLevel.Info, "Mouse", "Click the rate grid\r\nMouse Left Click item 'ShippingDlg.SplitContainer.RateGrid' at Center.", repo.ShippingDlg.SplitContainer.RateGridInfo, new RecordItemIndex(40));
            repo.ShippingDlg.SplitContainer.RateGrid.Click();
            
            // Verify the correct error message shows up in the footer of the rate area
            Report.Log(ReportLevel.Info, "Validation", "Verify the correct error message shows up in the footer of the rate area\r\nValidating AttributeEqual (RawText='Some errors occurred while getting rates.') on item 'ShippingDlg.SplitContainer.SomeErrorsOccurredWhileGettingRates'.", repo.ShippingDlg.SplitContainer.SomeErrorsOccurredWhileGettingRatesInfo, new RecordItemIndex(41));
            Validate.Attribute(repo.ShippingDlg.SplitContainer.SomeErrorsOccurredWhileGettingRatesInfo, "RawText", "Some errors occurred while getting rates.");
            
            // Close the Ship Orders UI
            Report.Log(ReportLevel.Info, "Mouse", "Close the Ship Orders UI\r\nMouse Left Click item 'ShippingDlg.Close' at Center.", repo.ShippingDlg.CloseInfo, new RecordItemIndex(42));
            repo.ShippingDlg.Close.Click();
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
