///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ShippingCarrierRegression
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SetupBestRate recording.
    /// </summary>
    [TestModule("005ab554-aa0e-4b7a-97ee-75c20ba4c7d1", ModuleType.Recording, 1)]
    public partial class SetupBestRate : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SmokeTest.SmokeTestRepository repository.
        /// </summary>
        public static SmokeTest.SmokeTestRepository repo = SmokeTest.SmokeTestRepository.Instance;

        static SetupBestRate instance = new SetupBestRate();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SetupBestRate()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SetupBestRate Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // Click the Manage Ribbon
            Report.Log(ReportLevel.Info, "Mouse", "Click the Manage Ribbon\r\nMouse Left Click item 'MainForm.Manage' at Center.", repo.MainForm.ManageInfo, new RecordItemIndex(0));
            repo.MainForm.Manage.Click();
            Delay.Milliseconds(200);
            
            // Click the Shipping Settings button
            Report.Log(ReportLevel.Info, "Mouse", "Click the Shipping Settings button\r\nMouse Left Click item 'MainForm.Shipping' at Center.", repo.MainForm.ShippingInfo, new RecordItemIndex(1));
            repo.MainForm.Shipping.Click();
            Delay.Milliseconds(200);
            
            // Check the Best Rate checkbox on the Shipping Settings Window
            Report.Log(ReportLevel.Info, "Invoke Action", "Check the Best Rate checkbox on the Shipping Settings Window\r\nInvoking Check() on item 'ShippingSettingsDlg.BestRate'.", repo.ShippingSettingsDlg.BestRateInfo, new RecordItemIndex(2));
            repo.ShippingSettingsDlg.BestRate.Check();
            Delay.Milliseconds(0);
            
            // Click the Best Rate button on the sidebar of the Shipping Settings Window
            Report.Log(ReportLevel.Info, "Mouse", "Click the Best Rate button on the sidebar of the Shipping Settings Window\r\nMouse Left Click item 'ShippingSettingsDlg.BestRate1' at Center.", repo.ShippingSettingsDlg.BestRate1Info, new RecordItemIndex(3));
            repo.ShippingSettingsDlg.BestRate1.Click();
            Delay.Milliseconds(200);
            
            // Click the Shipments tab on the Best Rate section of the Shipping Settings Window
            Report.Log(ReportLevel.Info, "Mouse", "Click the Shipments tab on the Best Rate section of the Shipping Settings Window\r\nMouse Left Click item 'ShippingSettingsDlg.TabControl.Shipments' at Center.", repo.ShippingSettingsDlg.TabControl.ShipmentsInfo, new RecordItemIndex(4));
            repo.ShippingSettingsDlg.TabControl.Shipments.Click();
            Delay.Milliseconds(200);
            
            // Click Close on the Shipping Settings window
            Report.Log(ReportLevel.Info, "Mouse", "Click Close on the Shipping Settings window\r\nMouse Left Click item 'ShippingSettingsDlg.Close' at Center.", repo.ShippingSettingsDlg.CloseInfo, new RecordItemIndex(5));
            repo.ShippingSettingsDlg.Close.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
