///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SoakPerformanceTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Express1InternationalErrorOK recording.
    /// </summary>
    [TestModule("fb76ccc2-e7b9-4457-b5b0-787057ed76ff", ModuleType.Recording, 1)]
    public partial class Express1InternationalErrorOK : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SoakPerformanceTestRepository repository.
        /// </summary>
        public static SoakPerformanceTestRepository repo = SoakPerformanceTestRepository.Instance;

        static Express1InternationalErrorOK instance = new Express1InternationalErrorOK();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Express1InternationalErrorOK()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Express1InternationalErrorOK Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ShipWorksSa.SomeErrorsOccurredDuringProcessing'.", repo.ShipWorksSa.SomeErrorsOccurredDuringProcessingInfo, new RecordItemIndex(0));
            Validate.Exists(repo.ShipWorksSa.SomeErrorsOccurredDuringProcessingInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShipWorksSa.ButtonOK1' at Center.", repo.ShipWorksSa.ButtonOK1Info, new RecordItemIndex(1));
            repo.ShipWorksSa.ButtonOK1.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
