///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SoakPerformanceTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ProcessOtherShipment recording.
    /// </summary>
    [TestModule("00418c08-356f-4b0e-b1e9-9372b9a6cefc", ModuleType.Recording, 1)]
    public partial class ProcessOtherShipment : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SmokeTestRepository repository.
        /// </summary>
        public static SmokeTestRepository repo = SmokeTestRepository.Instance;

        static ProcessOtherShipment instance = new ProcessOtherShipment();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ProcessOtherShipment()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ProcessOtherShipment Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShipOrders1.SplitContainer.Carrier' at Center.", repo.ShipOrders1.SplitContainer.CarrierInfo, new RecordItemIndex(0));
            repo.ShipOrders1.SplitContainer.Carrier.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}C{LShiftKey up}arrier' with focus on 'ShipOrders1.SplitContainer.Carrier'.", repo.ShipOrders1.SplitContainer.CarrierInfo, new RecordItemIndex(1));
            repo.ShipOrders1.SplitContainer.Carrier.PressKeys("{LShiftKey down}C{LShiftKey up}arrier");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShipOrders1.SplitContainer.Service1' at Center.", repo.ShipOrders1.SplitContainer.Service1Info, new RecordItemIndex(2));
            repo.ShipOrders1.SplitContainer.Service1.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}s{LShiftKey up}ervice' with focus on 'ShipOrders1.SplitContainer.Service1'.", repo.ShipOrders1.SplitContainer.Service1Info, new RecordItemIndex(3));
            repo.ShipOrders1.SplitContainer.Service1.PressKeys("{LShiftKey down}s{LShiftKey up}ervice");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShipOrders1.SplitContainer.WeightOther' at Center.", repo.ShipOrders1.SplitContainer.WeightOtherInfo, new RecordItemIndex(4));
            repo.ShipOrders1.SplitContainer.WeightOther.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'ShipOrders1.SplitContainer.WeightOther'.", repo.ShipOrders1.SplitContainer.WeightOtherInfo, new RecordItemIndex(5));
            Keyboard.PrepareFocus(repo.ShipOrders1.SplitContainer.WeightOther);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '50' with focus on 'ShipOrders1.SplitContainer.WeightOther'.", repo.ShipOrders1.SplitContainer.WeightOtherInfo, new RecordItemIndex(6));
            repo.ShipOrders1.SplitContainer.WeightOther.PressKeys("50");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShipOrders1.SplitContainer.Cost' at Center.", repo.ShipOrders1.SplitContainer.CostInfo, new RecordItemIndex(7));
            repo.ShipOrders1.SplitContainer.Cost.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'ShipOrders1.SplitContainer.Cost'.", repo.ShipOrders1.SplitContainer.CostInfo, new RecordItemIndex(8));
            Keyboard.PrepareFocus(repo.ShipOrders1.SplitContainer.Cost);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '5' with focus on 'ShipOrders1.SplitContainer.Cost'.", repo.ShipOrders1.SplitContainer.CostInfo, new RecordItemIndex(9));
            repo.ShipOrders1.SplitContainer.Cost.PressKeys("5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ShipOrders1.SplitContainer.TrackingHash' at Center.", repo.ShipOrders1.SplitContainer.TrackingHashInfo, new RecordItemIndex(10));
            repo.ShipOrders1.SplitContainer.TrackingHash.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '12345' with focus on 'ShipOrders1.SplitContainer.TrackingHash'.", repo.ShipOrders1.SplitContainer.TrackingHashInfo, new RecordItemIndex(11));
            repo.ShipOrders1.SplitContainer.TrackingHash.PressKeys("12345");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
