///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SoakPerformanceTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SetupAmazon recording.
    /// </summary>
    [TestModule("7017d1c2-7b45-4189-beb4-4089f07c862e", ModuleType.Recording, 1)]
    public partial class SetupAmazon : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SmokeTestRepository repository.
        /// </summary>
        public static SmokeTestRepository repo = SmokeTestRepository.Instance;

        static SetupAmazon instance = new SetupAmazon();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SetupAmazon()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SetupAmazon Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            // Testing Edits
            Report.Log(ReportLevel.Info, "Set Value", "Testing Edits\r\nSetting attribute ControlText to 'Amazon' on item 'AddStoreWizard.MainPanel.ComboStoreType'.", repo.AddStoreWizard.MainPanel.ComboStoreTypeInfo, new RecordItemIndex(0));
            repo.AddStoreWizard.MainPanel.ComboStoreType.Element.SetAttributeValue("ControlText", "Amazon");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(1));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddStoreWizard.Next' at Center.", repo.AddStoreWizard.NextInfo, new RecordItemIndex(2));
            repo.AddStoreWizard.Next.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(3));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddStoreWizard.Next' at Center.", repo.AddStoreWizard.NextInfo, new RecordItemIndex(4));
            repo.AddStoreWizard.Next.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(5));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddStoreWizard.MainPanel.SellerID' at Center.", repo.AddStoreWizard.MainPanel.SellerIDInfo, new RecordItemIndex(6));
            repo.AddStoreWizard.MainPanel.SellerID.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'A2OIXR4TA6XKOD' with focus on 'AddStoreWizard.MainPanel.SellerID'.", repo.AddStoreWizard.MainPanel.SellerIDInfo, new RecordItemIndex(7));
            repo.AddStoreWizard.MainPanel.SellerID.PressKeys("A2OIXR4TA6XKOD");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddStoreWizard.MainPanel.AuthToken' at Center.", repo.AddStoreWizard.MainPanel.AuthTokenInfo, new RecordItemIndex(8));
            repo.AddStoreWizard.MainPanel.AuthToken.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'amzn.mws.bea3ff6d-f837-212e-42e9-4888a7ed5ff9' with focus on 'AddStoreWizard.MainPanel.AuthToken'.", repo.AddStoreWizard.MainPanel.AuthTokenInfo, new RecordItemIndex(9));
            repo.AddStoreWizard.MainPanel.AuthToken.PressKeys("amzn.mws.bea3ff6d-f837-212e-42e9-4888a7ed5ff9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddStoreWizard.MainPanel.MarketplaceID' at Center.", repo.AddStoreWizard.MainPanel.MarketplaceIDInfo, new RecordItemIndex(10));
            repo.AddStoreWizard.MainPanel.MarketplaceID.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ATVPDKIKX0DER' with focus on 'AddStoreWizard.MainPanel.MarketplaceID'.", repo.AddStoreWizard.MainPanel.MarketplaceIDInfo, new RecordItemIndex(11));
            repo.AddStoreWizard.MainPanel.MarketplaceID.PressKeys("ATVPDKIKX0DER");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(12));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddStoreWizard.Next' at Center.", repo.AddStoreWizard.NextInfo, new RecordItemIndex(13));
            repo.AddStoreWizard.Next.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(14));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddStoreWizard.MainPanel.ExcludeFba' at Center.", repo.AddStoreWizard.MainPanel.ExcludeFbaInfo, new RecordItemIndex(15));
            repo.AddStoreWizard.MainPanel.ExcludeFba.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(16));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddStoreWizard.Next1' at Center.", repo.AddStoreWizard.Next1Info, new RecordItemIndex(17));
            repo.AddStoreWizard.Next1.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(18));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddStoreWizard.MainPanel.EnterYourShipWorksLicenseKeyToCont' at Center.", repo.AddStoreWizard.MainPanel.EnterYourShipWorksLicenseKeyToContInfo, new RecordItemIndex(19));
            repo.AddStoreWizard.MainPanel.EnterYourShipWorksLicenseKeyToCont.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'E6N7A-EAMRZ-AMXI2-1IHNL-AMAZON-BRIAN@INTERAPPTIVE.COM' with focus on 'AddStoreWizard.MainPanel.EnterYourShipWorksLicenseKeyToCont'.", repo.AddStoreWizard.MainPanel.EnterYourShipWorksLicenseKeyToContInfo, new RecordItemIndex(20));
            repo.AddStoreWizard.MainPanel.EnterYourShipWorksLicenseKeyToCont.PressKeys("E6N7A-EAMRZ-AMXI2-1IHNL-AMAZON-BRIAN@INTERAPPTIVE.COM");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(21));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddStoreWizard.Next' at Center.", repo.AddStoreWizard.NextInfo, new RecordItemIndex(22));
            repo.AddStoreWizard.Next.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(23));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddStoreWizard.MainPanel.StoreName' at Center.", repo.AddStoreWizard.MainPanel.StoreNameInfo, new RecordItemIndex(24));
            repo.AddStoreWizard.MainPanel.StoreName.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Amazon Store' with focus on 'AddStoreWizard.MainPanel.StoreName'.", repo.AddStoreWizard.MainPanel.StoreNameInfo, new RecordItemIndex(25));
            repo.AddStoreWizard.MainPanel.StoreName.PressKeys("Amazon Store");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(26));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddStoreWizard.Next' at Center.", repo.AddStoreWizard.NextInfo, new RecordItemIndex(27));
            repo.AddStoreWizard.Next.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(28));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddStoreWizard.Next' at Center.", repo.AddStoreWizard.NextInfo, new RecordItemIndex(29));
            repo.AddStoreWizard.Next.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(30));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddStoreWizard.MainPanel.EditDownloadDays' at Center.", repo.AddStoreWizard.MainPanel.EditDownloadDaysInfo, new RecordItemIndex(31));
            repo.AddStoreWizard.MainPanel.EditDownloadDays.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddStoreWizard.MainPanel.DateRangeDays' at Center.", repo.AddStoreWizard.MainPanel.DateRangeDaysInfo, new RecordItemIndex(32));
            repo.AddStoreWizard.MainPanel.DateRangeDays.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '30' on item 'AddStoreWizard.MainPanel.DateRangeDays'.", repo.AddStoreWizard.MainPanel.DateRangeDaysInfo, new RecordItemIndex(33));
            repo.AddStoreWizard.MainPanel.DateRangeDays.Element.SetAttributeValue("Text", "30");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddStoreWizard.MainPanel.CreateTask' at Center.", repo.AddStoreWizard.MainPanel.CreateTaskInfo, new RecordItemIndex(34));
            repo.AddStoreWizard.MainPanel.CreateTask.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(35));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddStoreWizard.Next' at Center.", repo.AddStoreWizard.NextInfo, new RecordItemIndex(36));
            repo.AddStoreWizard.Next.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(37));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddStoreWizard.Finish' at Center.", repo.AddStoreWizard.FinishInfo, new RecordItemIndex(38));
            repo.AddStoreWizard.Finish.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(39));
            Delay.Duration(500, false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s for item 'ProgressDlg' to not exist.", repo.ProgressDlg.SelfInfo, new ActionTimeout(30000), new RecordItemIndex(40));
            repo.ProgressDlg.SelfInfo.WaitForNotExists(30000);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (RawText='Amazon (Amazon Store)') on item 'MainForm.AmazonAmazonStore'.", repo.MainForm.AmazonAmazonStoreInfo, new RecordItemIndex(41));
            Validate.Attribute(repo.MainForm.AmazonAmazonStoreInfo, "RawText", "Amazon (Amazon Store)");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
