{
    "meta": {
        "status": 200,
		"success": true
    },
	"data": {
	    "id": 1,
		"name": "Baseball cap",
		"shop_product_type_id": 1,
		"shop_manufacturer_id": null,
		"shop_tax_class_id": 1,
		"title": null,
		"sku": "cap",
		"description": "<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.<\/p>\r\n<p>&nbsp;<\/p>",
		"short_description": null,
		"meta_description": null,
		"meta_keywords": null,
		"url_name": "cap",
		"base_price": 39.99,
		"cost": null,
		"depth": null,
		"width": null,
		"height": null,
		"weight": 2,
		"enabled": 1,
		"is_on_sale": 0,
		"sale_price_or_discount": null,
		"track_inventory": 0,
		"allow_preorder": 0,
		"in_stock_amount": null,
		"hide_out_of_stock": 0,
		"out_of_stock_threshold": 0,
		"low_stock_threshold": null,
		"expected_availability_date": null,
		"allow_negative_stock": 0,
		"is_catalog_visible": 1,
		"is_search_visible": 1,
		"created_by": null,
		"updated_by": null,
		"created_at": "2015-09-02T09:41:05-0700",
		"updated_at": "2015-09-08T09:42:28-0700"
	}
}