{
    "id": 36,
    "shop_order_id": null,
    "shop_order_status_id": 2,
    "shop_customer_id": 34,
    "status": "",
    "number": 36,
    "is_quote": 0,
    "is_tax_exempt": 0,
    "total": 45.08,
    "total_invoiced": 45.08,
    "total_paid": 45.08,
    "total_refunded": null,
    "subtotal_invoiced": 39.99,
    "subtotal_paid": 39.99,
    "subtotal_refunded": null,
    "total_discount": 0,
    "total_sales_tax": 0,
    "total_sales_tax_invoiced": 0,
    "total_sales_tax_paid": 0,
    "total_sales_tax_refunded": null,
    "total_shipping_tax": 0,
    "total_shipping_tax_invoiced": 0,
    "total_shipping_tax_paid": 0,
    "total_shipping_tax_refunded": null,
    "total_shipping_quote": 5.09,
    "total_shipping_invoiced": 5.09,
    "total_shipping_paid": 5.09,
    "total_shipping_refunded": null,
    "status_updated_at": "2015-09-10T11:59:06-0700",
    "created_by": null,
    "updated_by": null,
    "created_at": "2015-09-10T11:59:06-0700",
    "updated_at": "2015-09-10T11:59:06-0700",
    "customer": {
        "data": {
            "id": 34,
            "first_name": "",
            "last_name": "Marsh",
            "email": "chris.hicks1991@gmail.com",
            "notes": null,
            "is_guest": 1,
            "created_by": null,
            "updated_by": null,
            "created_at": "2015-09-10T11:59:06-0700",
            "updated_at": "2015-09-10T11:59:06-0700"
        }
    },
		"invoices": {
		    "data": [{
		        "id": 36,
		        "shop_order_id": 36,
		        "number": 1,
		        "shop_invoice_status_id": 2,
		        "status": "",
		        "subtotal": 39.99,
		        "total_shipping_quote": 5.09,
		        "tax_total": 0,
		        "total_discount": 0,
		        "total": 45.08,
		        "created_by": null,
		        "updated_by": null,
		        "created_at": "2015-09-10T11:59:06-0700",
		        "updated_at": "2015-09-10T11:59:06-0700"
		    }]
		},
		"items": {
		    "data": [{
		        "id": 40,
		        "shop_order_id": 36,
		        "shop_product_id": 1,
		        "shop_tax_class_id": 1,
		        "name": "Baseball cap",
		        "description": null,
		        "quantity": ,
		        "original_price": 39.99,
		        "price": 39.99,
		        "base_price": 39.99,
		        "cost": null,
		        "discount": 0,
		        "total": 39.99,
		        "options": null,
		        "extras": null
		    }]
		}
}