//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace ShipWorks.Shipping.Carriers.OnTrac.Schemas.Shipment {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("OnTracShipmentResponse", Namespace="", IsNullable=true)]
    public partial class ShipmentResponseList {
        
        private string errorField;
        
        private ShipmentResponse[] shipmentsField;
        
        /// <remarks/>
        public string Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Shipment")]
        public ShipmentResponse[] Shipments {
            get {
                return this.shipmentsField;
            }
            set {
                this.shipmentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ShipmentResponse {
        
        private string uIDField;
        
        private string trackingField;
        
        private string errorField;
        
        private int transitDaysField;
        
        private double serviceChrgField;
        
        private double fuelChrgField;
        
        private double totalChrgField;
        
        private double tariffChrgField;
        
        private string labelField;
        
        private string sortCodeField;
        
        /// <remarks/>
        public string UID {
            get {
                return this.uIDField;
            }
            set {
                this.uIDField = value;
            }
        }
        
        /// <remarks/>
        public string Tracking {
            get {
                return this.trackingField;
            }
            set {
                this.trackingField = value;
            }
        }
        
        /// <remarks/>
        public string Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        public int TransitDays {
            get {
                return this.transitDaysField;
            }
            set {
                this.transitDaysField = value;
            }
        }
        
        /// <remarks/>
        public double ServiceChrg {
            get {
                return this.serviceChrgField;
            }
            set {
                this.serviceChrgField = value;
            }
        }
        
        /// <remarks/>
        public double FuelChrg {
            get {
                return this.fuelChrgField;
            }
            set {
                this.fuelChrgField = value;
            }
        }
        
        /// <remarks/>
        public double TotalChrg {
            get {
                return this.totalChrgField;
            }
            set {
                this.totalChrgField = value;
            }
        }
        
        /// <remarks/>
        public double TariffChrg {
            get {
                return this.tariffChrgField;
            }
            set {
                this.tariffChrgField = value;
            }
        }
        
        /// <remarks/>
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        public string SortCode {
            get {
                return this.sortCodeField;
            }
            set {
                this.sortCodeField = value;
            }
        }
    }
}
