
-- ShipWorks V2 to V3 Database Migration Script, generated by CodeSmith
-- For table v2m_OrderItemAttributes

-- operational variables
DECLARE 
    @workCounter int,
    @newAttributeID bigint,
	@label varchar(100)

-- source table variables
DECLARE
    -- @MasterDatabase will be generated at runtime
    -- @IsArchive will be generated at runtime    
    @sAttributeID int, 
    @sRowVersion timestamp, 
    @sOrderItemID int, 
    @sCode nvarchar(300), 
    @sName nvarchar(300), 
    @sDescription nvarchar(1500), 
    @sUnitPrice money, 
    @sMivaAttributeID int, 
    @sMivaOptionCode nvarchar(300) 

-- target table variables
DECLARE
    @tOrderItemAttributeID bigint, 
    @tRowVersion timestamp, 
    @tOrderItemID bigint, 
    @tName nvarchar(300), 
    @tDescription nvarchar(max), 
    @tUnitPrice money 

-- Track Progress
SET @workCounter = 0

-- the cursor for cycling through the source table
DECLARE workCursor CURSOR FORWARD_ONLY FOR
SELECT TOP 1000
    [AttributeID],
    [RowVersion],
    [OrderItemID],
    [Code],
    [Name],
    [Description],
    [UnitPrice],
    [MivaAttributeID],
    [MivaOptionCode]
    FROM dbo.v2m_OrderItemAttributes

-- open the source table cursor
OPEN workCursor

-- populate source table variables from the source cursor
FETCH NEXT FROM workCursor
INTO
    @sAttributeID,
    @sRowVersion,
    @sOrderItemID,
    @sCode,
    @sName,
    @sDescription,
    @sUnitPrice,
    @sMivaAttributeID,
    @sMivaOptionCode
WHILE @@FETCH_STATUS = 0
BEGIN
    SET @workCounter = @workCounter + 1

    -- 
    -- Custom stuff here
    -- 
    SET @tOrderItemID = dbo.v2m_TranslateKey(@sOrderItemID, 4)
    SET @tName = @sName
    SET @tDescription = @sDescription
    SET @tUnitPrice = @sUnitPrice

    INSERT INTO {MASTERDATABASE}.dbo.OrderItemAttribute  (
	    [OrderItemID],
	    [Name],
	    [Description],
	    [UnitPrice]
    )
    VALUES
    (
	    @tOrderItemID,
	    @tName,
	    @tDescription,
	    @tUnitPrice
    )             
    
    -- 
    SET @newAttributeID = @@IDENTITY
    
    -- record the id
    exec dbo.v2m_RecordKey @sAttributeID, 9, @newAttributeID

	-- record an object label		
	SET @label = LEFT(@tName, 100)
	EXEC dbo.v2m_RecordObjectLabel @newAttributeID, 20, @tOrderItemID, @label
    
    -- Set Miva-specific fields aide for user later in the upgrader
	INSERT INTO {MASTERDATABASE}.dbo.v2m_MivaItemAttribute (
		[OrderItemAttributeID],
		[MivaAttributeID],
		[MivaOptionCode],
		[MivaAttributeCode]
	)
	VALUES
	(
		@newAttributeID,
		@sMivaAttributeID,
		@sMivaOptionCode,
		@sCode
	)
    
    -- delete from the old table and continue
    DELETE FROM dbo.v2m_OrderItemAttributes WHERE AttributeID = @sAttributeID
    
-- fetch next row from source table
FETCH NEXT FROM workCursor
INTO
    @sAttributeID,
    @sRowVersion,
    @sOrderItemID,
    @sCode,
    @sName,
    @sDescription,
    @sUnitPrice,
    @sMivaAttributeID,
    @sMivaOptionCode
END
CLOSE workCursor
DEALLOCATE workCursor

-- data migration "protocol" demands we return the number of rows/work completed
SELECT @workCounter as WorkCompleted