
-- ShipWorks V2 to V3 Database Migration Script, generated by CodeSmith
-- For table v2m_FedexClosings

-- operational variables
DECLARE 
    @workCounter int

-- source table variables
DECLARE
    -- @MasterDatabase will be generated at runtime
    -- @IsArchive will be generated at runtime    
    @sClosingID int, 
    @sShipperID int, 
    @sShipperAccountNumber int, 
    @sCloseDate datetime, 
    @sReportPaths nvarchar(450) 

-- target table variables
DECLARE
    @tFedExEndOfDayCloseID bigint, 
    @tFedExAccountID bigint, 
    @tAccountNumber nvarchar(50), 
    @tCloseDate datetime 

-- Track Progress
SET @workCounter = 0

-- the cursor for cycling through the source table
DECLARE workCursor CURSOR FORWARD_ONLY FOR
SELECT TOP 1000
        [ClosingID],
        [ShipperID],
        [ShipperAccountNumber],
        [CloseDate],
        [ReportPaths]
    FROM v2m_FedexClosings

-- open the source table cursor
OPEN workCursor

-- populate source table variables from the source cursor
FETCH NEXT FROM workCursor
INTO
        @sClosingID,
        @sShipperID,
        @sShipperAccountNumber,
        @sCloseDate,
        @sReportPaths
WHILE @@FETCH_STATUS = 0
BEGIN
    SET @workCounter = @workCounter + 1

    SET @tFedExAccountID = 0 
    SET @tAccountNumber = CAST(@sShipperAccountNumber as nvarchar(50))
    SET @tCloseDate = @sCloseDate

    INSERT INTO {MASTERDATABASE}.dbo.FedExEndOfDayClose  (
        [FedExAccountID],
        [AccountNumber],
        [CloseDate]
    )
    VALUES
    (
        @tFedExAccountID,
        @tAccountNumber,
        @tCloseDate
    )             
    
    -- delete the old closing
    DELETE FROM dbo.v2m_FedexClosings WHERE ClosingID = @sClosingID

-- fetch next row from source table
FETCH NEXT FROM workCursor
INTO
        @sClosingID,
        @sShipperID,
        @sShipperAccountNumber,
        @sCloseDate,
        @sReportPaths
END
CLOSE workCursor
DEALLOCATE workCursor

-- data migration "protocol" demands we return the number of rows/work completed
SELECT @workCounter as WorkCompleted