CREATE TABLE [dbo].[FedExProfile] (
    [ShippingProfileID]              BIGINT         NOT NULL,
    [FedExAccountID]                 BIGINT         NULL,
    [Service]                        INT            NULL,
    [Signature]                      INT            NULL,
    [PackagingType]                  INT            NULL,
    [NonStandardContainer]           BIT            NULL,
    [ReferenceCustomer]              NVARCHAR (300) NULL,
    [ReferenceInvoice]               NVARCHAR (300) NULL,
    [ReferencePO]                    NVARCHAR (300) NULL,
    [PayorTransportType]             INT            NULL,
    [PayorTransportAccount]          VARCHAR (12)   NULL,
    [PayorDutiesType]                INT            NULL,
    [PayorDutiesAccount]             VARCHAR (12)   NULL,
    [SaturdayDelivery]               BIT            NULL,
    [EmailNotifySender]              INT            NULL,
    [EmailNotifyRecipient]           INT            NULL,
    [EmailNotifyOther]               INT            NULL,
    [EmailNotifyOtherAddress]        NVARCHAR (100) NULL,
    [EmailNotifyMessage]             VARCHAR (120)  NULL,
    [ResidentialDetermination]       INT            NULL,
    [SmartPostIndicia]               INT            NULL,
    [SmartPostEndorsement]           INT            NULL,
    [SmartPostConfirmation]          BIT            NULL,
    [SmartPostCustomerManifest]      NVARCHAR (50)  NULL,
    [SmartPostHubID]                 VARCHAR (10)   NULL,
    [EmailNotifyBroker]              INT            NULL,
    [DropoffType]                    INT            NULL,
    [OriginResidentialDetermination] INT            NULL,
    [PayorTransportName]             NCHAR (60)     NULL,
    [ReturnType]                     INT            NULL,
    [RmaNumber]                      NVARCHAR (30)  NULL,
    [RmaReason]                      NVARCHAR (60)  NULL,
    [ReturnSaturdayPickup]           BIT            NULL,
    CONSTRAINT [PK_FedExProfile] PRIMARY KEY CLUSTERED ([ShippingProfileID] ASC),
    CONSTRAINT [FK_FedExProfile_ShippingProfile] FOREIGN KEY ([ShippingProfileID]) REFERENCES [dbo].[ShippingProfile] ([ShippingProfileID]) ON DELETE CASCADE
);

