CREATE TABLE [dbo].[FedExProfilePackage] (
    [FedExProfilePackageID]               BIGINT          IDENTITY (1062, 1000) NOT NULL,
    [ShippingProfileID]                   BIGINT          NOT NULL,
    [Weight]                              FLOAT (53)      NULL,
    [DimsProfileID]                       BIGINT          NULL,
    [DimsLength]                          FLOAT (53)      NULL,
    [DimsWidth]                           FLOAT (53)      NULL,
    [DimsHeight]                          FLOAT (53)      NULL,
    [DimsWeight]                          FLOAT (53)      NULL,
    [DimsAddWeight]                       BIT             NULL,
    [PriorityAlert]                       BIT             NULL,
    [PriorityAlertEnhancementType]        INT             NULL,
    [PriorityAlertDetailContent]          NVARCHAR (1024) NULL,
    [DryIceWeight]                        FLOAT (53)      NULL,
    [ContainsAlcohol]                     BIT             NULL,
    [DangerousGoodsEnabled]               BIT             NULL,
    [DangerousGoodsType]                  INT             NULL,
    [DangerousGoodsAccessibilityType]     INT             NULL,
    [DangerousGoodsCargoAircraftOnly]     BIT             NULL,
    [DangerousGoodsEmergencyContactPhone] NVARCHAR (16)   NULL,
    [DangerousGoodsOfferor]               NVARCHAR (128)  NULL,
    [DangerousGoodsPackagingCount]        INT             NULL,
    [HazardousMaterialNumber]             NVARCHAR (16)   NULL,
    [HazardousMaterialClass]              NVARCHAR (8)    NULL,
    [HazardousMaterialProperName]         NVARCHAR (64)   NULL,
    [HazardousMaterialPackingGroup]       INT             NULL,
    [HazardousMaterialQuantityValue]      FLOAT (53)      NULL,
    [HazardousMaterialQuanityUnits]       INT             NULL,
    CONSTRAINT [PK_FedExProfilePackage] PRIMARY KEY CLUSTERED ([FedExProfilePackageID] ASC),
    CONSTRAINT [FK_FedExProfilePackage_FedExProfile] FOREIGN KEY ([ShippingProfileID]) REFERENCES [dbo].[FedExProfile] ([ShippingProfileID]) ON DELETE CASCADE
);

