CREATE TABLE [dbo].[GenericFileStore] (
    [StoreID]                  BIGINT         NOT NULL,
    [FileFormat]               INT            NOT NULL,
    [FileSource]               INT            NOT NULL,
    [DiskFolder]               NVARCHAR (355) NOT NULL,
    [FtpAccountID]             BIGINT         NULL,
    [FtpFolder]                NVARCHAR (355) NOT NULL,
    [EmailAccountID]           BIGINT         NULL,
    [EmailFolder]              NVARCHAR (100) CONSTRAINT [DF_GenericFileStore_EmailIncomingFolder] DEFAULT ('') NOT NULL,
    [EmailFolderValidityID]    BIGINT         NOT NULL,
    [EmailFolderLastMessageID] BIGINT         NOT NULL,
    [EmailOnlyUnread]          BIT            NOT NULL,
    [NamePatternMatch]         NVARCHAR (50)  NULL,
    [NamePatternSkip]          NVARCHAR (50)  NULL,
    [SuccessAction]            INT            NOT NULL,
    [SuccessMoveFolder]        NVARCHAR (355) NOT NULL,
    [ErrorAction]              INT            NOT NULL,
    [ErrorMoveFolder]          NVARCHAR (355) NOT NULL,
    [XmlXsltFileName]          NVARCHAR (355) NULL,
    [XmlXsltContent]           NTEXT          NULL,
    [FlatImportMap]            NTEXT          NOT NULL,
    CONSTRAINT [PK_GenericFileStore] PRIMARY KEY CLUSTERED ([StoreID] ASC),
    CONSTRAINT [FK_GenericFileStore_Store] FOREIGN KEY ([StoreID]) REFERENCES [dbo].[Store] ([StoreID])
);

