CREATE TABLE [dbo].[OnTracShipment] (
    [ShipmentID]        BIGINT         NOT NULL,
    [OnTracAccountID]   BIGINT         NOT NULL,
    [Service]           INT            NOT NULL,
    [IsCod]             BIT            NOT NULL,
    [CodType]           INT            NOT NULL,
    [CodAmount]         MONEY          NOT NULL,
    [SaturdayDelivery]  BIT            NOT NULL,
    [SignatureRequired] BIT            NOT NULL,
    [PackagingType]     INT            NOT NULL,
    [Instructions]      NVARCHAR (300) NOT NULL,
    [DimsProfileID]     BIGINT         NOT NULL,
    [DimsLength]        FLOAT (53)     NOT NULL,
    [DimsWidth]         FLOAT (53)     NOT NULL,
    [DimsHeight]        FLOAT (53)     NOT NULL,
    [DimsWeight]        FLOAT (53)     NOT NULL,
    [DimsAddWeight]     BIT            NOT NULL,
    [Reference1]        NVARCHAR (300) NOT NULL,
    [Reference2]        NVARCHAR (300) NOT NULL,
    [InsuranceValue]    MONEY          NOT NULL,
    [InsurancePennyOne] BIT            NOT NULL,
    [DeclaredValue]     MONEY          NOT NULL,
    CONSTRAINT [PK_OnTracShipment] PRIMARY KEY CLUSTERED ([ShipmentID] ASC),
    CONSTRAINT [FK_OnTracShipment_Shipment] FOREIGN KEY ([ShipmentID]) REFERENCES [dbo].[Shipment] ([ShipmentID]) ON DELETE CASCADE
);

