CREATE TABLE [dbo].[Scheduling_CALENDARS] (
    [SCHED_NAME]    NVARCHAR (100) NOT NULL,
    [CALENDAR_NAME] NVARCHAR (200) NOT NULL,
    [CALENDAR]      IMAGE          NOT NULL,
    CONSTRAINT [PK_Scheduling_CALENDARS] PRIMARY KEY CLUSTERED ([SCHED_NAME] ASC, [CALENDAR_NAME] ASC)
);

