CREATE TABLE [dbo].[Scheduling_LOCKS] (
    [SCHED_NAME] NVARCHAR (100) NOT NULL,
    [LOCK_NAME]  NVARCHAR (40)  NOT NULL,
    CONSTRAINT [PK_Scheduling_LOCKS] PRIMARY KEY CLUSTERED ([SCHED_NAME] ASC, [LOCK_NAME] ASC)
);

