CREATE TABLE [dbo].[Scheduling_PAUSED_TRIGGER_GRPS] (
    [SCHED_NAME]    NVARCHAR (100) NOT NULL,
    [TRIGGER_GROUP] NVARCHAR (150) NOT NULL,
    CONSTRAINT [PK_Scheduling_PAUSED_TRIGGER_GRPS] PRIMARY KEY CLUSTERED ([SCHED_NAME] ASC, [TRIGGER_GROUP] ASC)
);

