CREATE TABLE [dbo].[Scheduling_BLOB_TRIGGERS] (
    [SCHED_NAME]    NVARCHAR (100) NOT NULL,
    [TRIGGER_NAME]  NVARCHAR (150) NOT NULL,
    [TRIGGER_GROUP] NVARCHAR (150) NOT NULL,
    [BLOB_DATA]     IMAGE          NULL
);

