CREATE TABLE [dbo].[UpsProfile] (
    [ShippingProfileID]                BIGINT         NOT NULL,
    [UpsAccountID]                     BIGINT         NULL,
    [Service]                          INT            NULL,
    [SaturdayDelivery]                 BIT            NULL,
    [ResidentialDetermination]         INT            NULL,
    [DeliveryConfirmation]             INT            NULL,
    [ReferenceNumber]                  NVARCHAR (300) NULL,
    [ReferenceNumber2]                 NVARCHAR (300) NULL,
    [PayorType]                        INT            NULL,
    [PayorAccount]                     VARCHAR (10)   NULL,
    [PayorPostalCode]                  NVARCHAR (20)  NULL,
    [PayorCountryCode]                 NVARCHAR (50)  NULL,
    [EmailNotifySender]                INT            NULL,
    [EmailNotifyRecipient]             INT            NULL,
    [EmailNotifyOther]                 INT            NULL,
    [EmailNotifyOtherAddress]          NVARCHAR (100) NULL,
    [EmailNotifyFrom]                  NVARCHAR (100) NULL,
    [EmailNotifySubject]               INT            NULL,
    [EmailNotifyMessage]               NVARCHAR (120) NULL,
    [ReturnService]                    INT            NULL,
    [ReturnUndeliverableEmail]         NVARCHAR (100) NULL,
    [ReturnContents]                   NVARCHAR (300) NULL,
    [Endorsement]                      INT            NULL,
    [Subclassification]                INT            NULL,
    [PaperlessAdditionalDocumentation] BIT            NULL,
    [ShipperRelease]                   BIT            NULL,
    [CarbonNeutral]                    BIT            NULL,
    [CommercialPaperlessInvoice]       BIT            NULL,
    [CostCenter]                       NVARCHAR (30)  NULL,
    [IrregularIndicator]               INT            NULL,
    [Cn22Number]                       NVARCHAR (255) NULL,
    [ShipmentChargeType]               INT            NULL,
    [ShipmentChargeAccount]            VARCHAR (10)   NULL,
    [ShipmentChargePostalCode]         NVARCHAR (20)  NULL,
    [ShipmentChargeCountryCode]        NVARCHAR (50)  NULL,
    [UspsPackageID]                    NVARCHAR (50)  NULL,
    CONSTRAINT [PK_UpsProfile] PRIMARY KEY CLUSTERED ([ShippingProfileID] ASC),
    CONSTRAINT [FK_UpsProfile_ShippingProfile] FOREIGN KEY ([ShippingProfileID]) REFERENCES [dbo].[ShippingProfile] ([ShippingProfileID]) ON DELETE CASCADE
);

