CREATE TABLE [dbo].[WorldShipShipment] (
    [ShipmentID]                    BIGINT         NOT NULL,
    [OrderNumber]                   NVARCHAR (50)  NOT NULL,
    [FromCompanyOrName]             NVARCHAR (35)  NOT NULL,
    [FromAttention]                 NVARCHAR (35)  NOT NULL,
    [FromAddress1]                  NVARCHAR (60)  NOT NULL,
    [FromAddress2]                  NVARCHAR (60)  NOT NULL,
    [FromAddress3]                  NVARCHAR (60)  NOT NULL,
    [FromCountryCode]               VARCHAR (50)   NOT NULL,
    [FromPostalCode]                VARCHAR (20)   NOT NULL,
    [FromCity]                      NVARCHAR (50)  NOT NULL,
    [FromStateProvCode]             VARCHAR (50)   NOT NULL,
    [FromTelephone]                 VARCHAR (25)   NOT NULL,
    [FromEmail]                     NVARCHAR (100) NOT NULL,
    [FromAccountNumber]             VARCHAR (10)   NOT NULL,
    [ToCustomerID]                  NVARCHAR (30)  NOT NULL,
    [ToCompanyOrName]               NVARCHAR (35)  NOT NULL,
    [ToAttention]                   NVARCHAR (35)  NOT NULL,
    [ToAddress1]                    NVARCHAR (60)  NOT NULL,
    [ToAddress2]                    NVARCHAR (60)  NOT NULL,
    [ToAddress3]                    NVARCHAR (60)  NOT NULL,
    [ToCountryCode]                 VARCHAR (50)   NOT NULL,
    [ToPostalCode]                  VARCHAR (20)   NOT NULL,
    [ToCity]                        NVARCHAR (50)  NOT NULL,
    [ToStateProvCode]               VARCHAR (50)   NOT NULL,
    [ToTelephone]                   VARCHAR (25)   NOT NULL,
    [ToEmail]                       NVARCHAR (100) NOT NULL,
    [ToAccountNumber]               VARCHAR (10)   NOT NULL,
    [ToResidential]                 CHAR (1)       NOT NULL,
    [ServiceType]                   VARCHAR (3)    NOT NULL,
    [BillTransportationTo]          VARCHAR (20)   NOT NULL,
    [SaturdayDelivery]              CHAR (1)       NOT NULL,
    [QvnOption]                     CHAR (1)       NOT NULL,
    [QvnFrom]                       NVARCHAR (35)  NULL,
    [QvnSubjectLine]                NVARCHAR (18)  NULL,
    [QvnMemo]                       NVARCHAR (150) NULL,
    [Qvn1ShipNotify]                CHAR (1)       NOT NULL,
    [Qvn1DeliveryNotify]            CHAR (1)       NOT NULL,
    [Qvn1ExceptionNotify]           CHAR (1)       NOT NULL,
    [Qvn1ContactName]               NVARCHAR (35)  NOT NULL,
    [Qvn1Email]                     NVARCHAR (100) NOT NULL,
    [Qvn2ShipNotify]                CHAR (1)       NOT NULL,
    [Qvn2DeliveryNotify]            CHAR (1)       NOT NULL,
    [Qvn2ExceptionNotify]           CHAR (1)       NOT NULL,
    [Qvn2ContactName]               NVARCHAR (35)  NOT NULL,
    [Qvn2Email]                     NVARCHAR (100) NOT NULL,
    [Qvn3ShipNotify]                CHAR (1)       NOT NULL,
    [Qvn3DeliveryNotify]            CHAR (1)       NOT NULL,
    [Qvn3ExceptionNotify]           CHAR (1)       NOT NULL,
    [Qvn3ContactName]               NVARCHAR (35)  NOT NULL,
    [Qvn3Email]                     NVARCHAR (100) NOT NULL,
    [CustomsDescriptionOfGoods]     NVARCHAR (150) NULL,
    [CustomsDocumentsOnly]          CHAR (1)       NULL,
    [ShipperNumber]                 VARCHAR (10)   NOT NULL,
    [PackageCount]                  INT            NOT NULL,
    [DeliveryConfirmation]          CHAR (1)       NOT NULL,
    [DeliveryConfirmationAdult]     CHAR (1)       NOT NULL,
    [InvoiceTermsOfSale]            VARCHAR (3)    NULL,
    [InvoiceReasonForExport]        VARCHAR (2)    NULL,
    [InvoiceComments]               NVARCHAR (200) NULL,
    [InvoiceCurrencyCode]           VARCHAR (3)    NULL,
    [InvoiceChargesFreight]         MONEY          NULL,
    [InvoiceChargesInsurance]       MONEY          NULL,
    [InvoiceChargesOther]           MONEY          NULL,
    [ShipmentProcessedOnComputerID] BIGINT         NULL,
    [UspsEndorsement]               NVARCHAR (50)  NULL,
    [CarbonNeutral]                 CHAR (10)      NULL,
    CONSTRAINT [PK_WorldShipShipment] PRIMARY KEY CLUSTERED ([ShipmentID] ASC),
    CONSTRAINT [FK_WorldShipShipment_UpsShipment] FOREIGN KEY ([ShipmentID]) REFERENCES [dbo].[UpsShipment] ([ShipmentID]) ON DELETE CASCADE
);

