///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace UIResponsiveness
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ProcessFedExInternational_ShippingPanel recording.
    /// </summary>
    [TestModule("90ab8097-d70e-4f7c-9458-788d542b3ff6", ModuleType.Recording, 1)]
    public partial class ProcessFedExInternational_ShippingPanel : ITestModule
    {
        /// <summary>
        /// Holds an instance of the UIResponsivenessRepository repository.
        /// </summary>
        public static UIResponsivenessRepository repo = UIResponsivenessRepository.Instance;

        static ProcessFedExInternational_ShippingPanel instance = new ProcessFedExInternational_ShippingPanel();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ProcessFedExInternational_ShippingPanel()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ProcessFedExInternational_ShippingPanel Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.5")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            // Shipping Panel Set provider: FedEx
            Report.Log(ReportLevel.Info, "Set Value", "Shipping Panel Set provider: FedEx\r\nSetting attribute SelectedItemText to 'FedEx' on item 'ShipWorksSa.PanelDockingArea.Provider'.", repo.ShipWorksSa.PanelDockingArea.ProviderInfo, new RecordItemIndex(0));
            repo.ShipWorksSa.PanelDockingArea.Provider.Element.SetAttributeValue("SelectedItemText", "FedEx");
            Delay.Milliseconds(0);
            
            // Give Focus: Country
            Report.Log(ReportLevel.Info, "Invoke Action", "Give Focus: Country\r\nInvoking Focus() on item 'ShipWorks2.ToCountry_ShippingPanel'.", repo.ShipWorks2.ToCountry_ShippingPanelInfo, new RecordItemIndex(1));
            repo.ShipWorks2.ToCountry_ShippingPanel.Focus();
            Delay.Milliseconds(0);
            
            // Click: Country
            Report.Log(ReportLevel.Info, "Mouse", "Click: Country\r\nMouse Left Click item 'ShipWorks2.ToCountry_ShippingPanel' at Center.", repo.ShipWorks2.ToCountry_ShippingPanelInfo, new RecordItemIndex(2));
            repo.ShipWorks2.ToCountry_ShippingPanel.Click();
            Delay.Milliseconds(200);
            
            // Set Country: France
            Report.Log(ReportLevel.Info, "Mouse", "Set Country: France\r\nMouse Left Click item 'ShipWorks.France' at Center.", repo.ShipWorks.FranceInfo, new RecordItemIndex(3));
            repo.ShipWorks.France.Click();
            Delay.Milliseconds(200);
            
            // Click: Postal Code
            Report.Log(ReportLevel.Info, "Mouse", "Click: Postal Code\r\nMouse Left Click item 'MainForm.PanelDockingArea.ToPostalCode_ShippingPanel2' at Center.", repo.MainForm.PanelDockingArea.ToPostalCode_ShippingPanel2Info, new RecordItemIndex(4));
            repo.MainForm.PanelDockingArea.ToPostalCode_ShippingPanel2.Click();
            Delay.Milliseconds(200);
            
            // Set Postal Code: 75009
            Report.Log(ReportLevel.Info, "Keyboard", "Set Postal Code: 75009\r\nKey sequence '{Home}{LShiftKey down}{End}{LShiftKey up}75009' with focus on 'MainForm.PanelDockingArea.ToPostalCode_ShippingPanel2'.", repo.MainForm.PanelDockingArea.ToPostalCode_ShippingPanel2Info, new RecordItemIndex(5));
            repo.MainForm.PanelDockingArea.ToPostalCode_ShippingPanel2.PressKeys("{Home}{LShiftKey down}{End}{LShiftKey up}75009");
            Delay.Milliseconds(0);
            
            // Click: State
            Report.Log(ReportLevel.Info, "Mouse", "Click: State\r\nMouse Left Click item 'MainForm.PanelDockingArea.ToState_ShippingPanel2' at Center.", repo.MainForm.PanelDockingArea.ToState_ShippingPanel2Info, new RecordItemIndex(6));
            repo.MainForm.PanelDockingArea.ToState_ShippingPanel2.Click();
            Delay.Milliseconds(200);
            
            // Set State: {BLANK}
            Report.Log(ReportLevel.Info, "Keyboard", "Set State: {BLANK}\r\nKey sequence '{Home}{LShiftKey down}{End}{LShiftKey up}{Delete}' with focus on 'MainForm.PanelDockingArea.ToState_ShippingPanel2'.", repo.MainForm.PanelDockingArea.ToState_ShippingPanel2Info, new RecordItemIndex(7));
            repo.MainForm.PanelDockingArea.ToState_ShippingPanel2.PressKeys("{Home}{LShiftKey down}{End}{LShiftKey up}{Delete}");
            Delay.Milliseconds(0);
            
            // Click: City
            Report.Log(ReportLevel.Info, "Mouse", "Click: City\r\nMouse Left Click item 'MainForm.PanelDockingArea.ToCity_ShippingPanel2' at Center.", repo.MainForm.PanelDockingArea.ToCity_ShippingPanel2Info, new RecordItemIndex(8));
            repo.MainForm.PanelDockingArea.ToCity_ShippingPanel2.Click();
            Delay.Milliseconds(200);
            
            // Set City: Paris
            Report.Log(ReportLevel.Info, "Keyboard", "Set City: Paris\r\nKey sequence '{Home}{LShiftKey down}{End}{LShiftKey up}Paris' with focus on 'MainForm.PanelDockingArea.ToCity_ShippingPanel2'.", repo.MainForm.PanelDockingArea.ToCity_ShippingPanel2Info, new RecordItemIndex(9));
            repo.MainForm.PanelDockingArea.ToCity_ShippingPanel2.PressKeys("{Home}{LShiftKey down}{End}{LShiftKey up}Paris");
            Delay.Milliseconds(0);
            
            // Give Focus: Weight
            Report.Log(ReportLevel.Info, "Invoke Action", "Give Focus: Weight\r\nInvoking Focus() on item 'ShipWorks2.Weight'.", repo.ShipWorks2.WeightInfo, new RecordItemIndex(10));
            repo.ShipWorks2.Weight.Focus();
            Delay.Milliseconds(0);
            
            // Set Weight: 1
            Report.Log(ReportLevel.Info, "Keyboard", "Set Weight: 1\r\nKey sequence '{End}{LShiftKey down}{Home}{LShiftKey up}1' with focus on 'ShipWorks2.Weight'.", repo.ShipWorks2.WeightInfo, new RecordItemIndex(11));
            repo.ShipWorks2.Weight.PressKeys("{End}{LShiftKey down}{Home}{LShiftKey up}1");
            Delay.Milliseconds(0);
            
            // Set Length: 6
            Report.Log(ReportLevel.Info, "Keyboard", "Set Length: 6\r\nKey sequence '{End}{LShiftKey down}{Home}{LShiftKey up}6' with focus on 'ShipWorks2.SomeContainer.Length'.", repo.ShipWorks2.SomeContainer.LengthInfo, new RecordItemIndex(12));
            repo.ShipWorks2.SomeContainer.Length.PressKeys("{End}{LShiftKey down}{Home}{LShiftKey up}6");
            Delay.Milliseconds(0);
            
            // Set Width: 7
            Report.Log(ReportLevel.Info, "Keyboard", "Set Width: 7\r\nKey sequence '{End}{LShiftKey down}{Home}{LShiftKey up}7' with focus on 'ShipWorks2.SomeContainer.Width'.", repo.ShipWorks2.SomeContainer.WidthInfo, new RecordItemIndex(13));
            repo.ShipWorks2.SomeContainer.Width.PressKeys("{End}{LShiftKey down}{Home}{LShiftKey up}7");
            Delay.Milliseconds(0);
            
            // Set Height: 8
            Report.Log(ReportLevel.Info, "Keyboard", "Set Height: 8\r\nKey sequence '{End}{LShiftKey down}{Home}{LShiftKey up}8' with focus on 'ShipWorks2.SomeContainer.Height'.", repo.ShipWorks2.SomeContainer.HeightInfo, new RecordItemIndex(14));
            repo.ShipWorks2.SomeContainer.Height.PressKeys("{End}{LShiftKey down}{Home}{LShiftKey up}8");
            Delay.Milliseconds(0);
            
            // Click: Add (Package)
            Report.Log(ReportLevel.Info, "Mouse", "Click: Add (Package)\r\nMouse Left Click item 'ShipWorks2.PanelDockingArea.AddCustomsItem_ShippingPanel' at Center.", repo.ShipWorks2.PanelDockingArea.AddCustomsItem_ShippingPanelInfo, new RecordItemIndex(15));
            repo.ShipWorks2.PanelDockingArea.AddCustomsItem_ShippingPanel.Click();
            Delay.Milliseconds(200);
            
            // Delay
            Report.Log(ReportLevel.Info, "Delay", "Delay\r\nWaiting for 500ms.", new RecordItemIndex(16));
            Delay.Duration(500, false);
            
            // Click: Add (Package)
            Report.Log(ReportLevel.Info, "Mouse", "Click: Add (Package)\r\nMouse Left Click item 'ShipWorks2.PanelDockingArea.AddCustomsItem_ShippingPanel' at Center.", repo.ShipWorks2.PanelDockingArea.AddCustomsItem_ShippingPanelInfo, new RecordItemIndex(17));
            repo.ShipWorks2.PanelDockingArea.AddCustomsItem_ShippingPanel.Click();
            Delay.Milliseconds(200);
            
            // Delay
            Report.Log(ReportLevel.Info, "Delay", "Delay\r\nWaiting for 500ms.", new RecordItemIndex(18));
            Delay.Duration(500, false);
            
            // Click: Delete (Package)
            Report.Log(ReportLevel.Info, "Mouse", "Click: Delete (Package)\r\nMouse Left Click item 'ShipWorks2.PanelDockingArea.DeleteCustomsItem_ShippingPanel' at Center.", repo.ShipWorks2.PanelDockingArea.DeleteCustomsItem_ShippingPanelInfo, new RecordItemIndex(19));
            repo.ShipWorks2.PanelDockingArea.DeleteCustomsItem_ShippingPanel.Click();
            Delay.Milliseconds(200);
            
            // Delay
            Report.Log(ReportLevel.Info, "Delay", "Delay\r\nWaiting for 500ms.", new RecordItemIndex(20));
            Delay.Duration(500, false);
            
            // Click: Customs Item Weight
            Report.Log(ReportLevel.Info, "Mouse", "Click: Customs Item Weight\r\nMouse Left Click item 'ShipWorks2.PanelDockingArea.CustomsItemWeight' at Center.", repo.ShipWorks2.PanelDockingArea.CustomsItemWeightInfo, new RecordItemIndex(21));
            repo.ShipWorks2.PanelDockingArea.CustomsItemWeight.Click();
            Delay.Milliseconds(200);
            
            // Set Customs Item Weight: 1
            Report.Log(ReportLevel.Info, "Keyboard", "Set Customs Item Weight: 1\r\nKey sequence '{End}{LShiftKey down}{Home}{LShiftKey up}1' with focus on 'ShipWorks2.PanelDockingArea.CustomsItemWeight'.", repo.ShipWorks2.PanelDockingArea.CustomsItemWeightInfo, new RecordItemIndex(22));
            repo.ShipWorks2.PanelDockingArea.CustomsItemWeight.PressKeys("{End}{LShiftKey down}{Home}{LShiftKey up}1");
            Delay.Milliseconds(0);
            
            // Click: Customs Item Value
            Report.Log(ReportLevel.Info, "Mouse", "Click: Customs Item Value\r\nMouse Left Click item 'ShipWorks2.PanelDockingArea.CustomsItemValue' at Center.", repo.ShipWorks2.PanelDockingArea.CustomsItemValueInfo, new RecordItemIndex(23));
            repo.ShipWorks2.PanelDockingArea.CustomsItemValue.Click();
            Delay.Milliseconds(200);
            
            // Set Customs Item Value: 5
            Report.Log(ReportLevel.Info, "Keyboard", "Set Customs Item Value: 5\r\nKey sequence '{End}{LShiftKey down}{Home}{LShiftKey up}5' with focus on 'ShipWorks2.PanelDockingArea.CustomsItemValue'.", repo.ShipWorks2.PanelDockingArea.CustomsItemValueInfo, new RecordItemIndex(24));
            repo.ShipWorks2.PanelDockingArea.CustomsItemValue.PressKeys("{End}{LShiftKey down}{Home}{LShiftKey up}5");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
