//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.235.
// 
#pragma warning disable 1591

namespace ShipWorks.Shipping.Carriers.EquaShip.WebServices {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EquashipAPISoap", Namespace="http://equaship.com/")]
    public partial class EquashipAPI : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetRatesAndTransitTimesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcessShipmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback TrackShipmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback VoidShipmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback ImportShipmentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback LocateDropOffPointsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EquashipAPI() {
            this.Url = "http://integrate.equaship.com/apidev/equashipapi.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetRatesAndTransitTimesCompletedEventHandler GetRatesAndTransitTimesCompleted;
        
        /// <remarks/>
        public event ProcessShipmentCompletedEventHandler ProcessShipmentCompleted;
        
        /// <remarks/>
        public event TrackShipmentCompletedEventHandler TrackShipmentCompleted;
        
        /// <remarks/>
        public event VoidShipmentCompletedEventHandler VoidShipmentCompleted;
        
        /// <remarks/>
        public event ImportShipmentsCompletedEventHandler ImportShipmentsCompleted;
        
        /// <remarks/>
        public event LocateDropOffPointsCompletedEventHandler LocateDropOffPointsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://equaship.com/GetRatesAndTransitTimes", RequestNamespace="http://equaship.com/", ResponseNamespace="http://equaship.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResponseToRatesAndTransitTimesRequest GetRatesAndTransitTimes(RatesAndTransitTimesRequest request) {
            object[] results = this.Invoke("GetRatesAndTransitTimes", new object[] {
                        request});
            return ((ResponseToRatesAndTransitTimesRequest)(results[0]));
        }
        
        /// <remarks/>
        public void GetRatesAndTransitTimesAsync(RatesAndTransitTimesRequest request) {
            this.GetRatesAndTransitTimesAsync(request, null);
        }
        
        /// <remarks/>
        public void GetRatesAndTransitTimesAsync(RatesAndTransitTimesRequest request, object userState) {
            if ((this.GetRatesAndTransitTimesOperationCompleted == null)) {
                this.GetRatesAndTransitTimesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRatesAndTransitTimesOperationCompleted);
            }
            this.InvokeAsync("GetRatesAndTransitTimes", new object[] {
                        request}, this.GetRatesAndTransitTimesOperationCompleted, userState);
        }
        
        private void OnGetRatesAndTransitTimesOperationCompleted(object arg) {
            if ((this.GetRatesAndTransitTimesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRatesAndTransitTimesCompleted(this, new GetRatesAndTransitTimesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://equaship.com/ProcessShipment", RequestNamespace="http://equaship.com/", ResponseNamespace="http://equaship.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResponseToShipmentRequest ProcessShipment(ShipmentRequest request) {
            object[] results = this.Invoke("ProcessShipment", new object[] {
                        request});
            return ((ResponseToShipmentRequest)(results[0]));
        }
        
        /// <remarks/>
        public void ProcessShipmentAsync(ShipmentRequest request) {
            this.ProcessShipmentAsync(request, null);
        }
        
        /// <remarks/>
        public void ProcessShipmentAsync(ShipmentRequest request, object userState) {
            if ((this.ProcessShipmentOperationCompleted == null)) {
                this.ProcessShipmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessShipmentOperationCompleted);
            }
            this.InvokeAsync("ProcessShipment", new object[] {
                        request}, this.ProcessShipmentOperationCompleted, userState);
        }
        
        private void OnProcessShipmentOperationCompleted(object arg) {
            if ((this.ProcessShipmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessShipmentCompleted(this, new ProcessShipmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://equaship.com/TrackShipment", RequestNamespace="http://equaship.com/", ResponseNamespace="http://equaship.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResponseToTrackShipmentRequest TrackShipment(TrackShipmentRequest request) {
            object[] results = this.Invoke("TrackShipment", new object[] {
                        request});
            return ((ResponseToTrackShipmentRequest)(results[0]));
        }
        
        /// <remarks/>
        public void TrackShipmentAsync(TrackShipmentRequest request) {
            this.TrackShipmentAsync(request, null);
        }
        
        /// <remarks/>
        public void TrackShipmentAsync(TrackShipmentRequest request, object userState) {
            if ((this.TrackShipmentOperationCompleted == null)) {
                this.TrackShipmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTrackShipmentOperationCompleted);
            }
            this.InvokeAsync("TrackShipment", new object[] {
                        request}, this.TrackShipmentOperationCompleted, userState);
        }
        
        private void OnTrackShipmentOperationCompleted(object arg) {
            if ((this.TrackShipmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TrackShipmentCompleted(this, new TrackShipmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://equaship.com/VoidShipment", RequestNamespace="http://equaship.com/", ResponseNamespace="http://equaship.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResponseToVoidShipmentRequest VoidShipment(VoidShipmentRequest request) {
            object[] results = this.Invoke("VoidShipment", new object[] {
                        request});
            return ((ResponseToVoidShipmentRequest)(results[0]));
        }
        
        /// <remarks/>
        public void VoidShipmentAsync(VoidShipmentRequest request) {
            this.VoidShipmentAsync(request, null);
        }
        
        /// <remarks/>
        public void VoidShipmentAsync(VoidShipmentRequest request, object userState) {
            if ((this.VoidShipmentOperationCompleted == null)) {
                this.VoidShipmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVoidShipmentOperationCompleted);
            }
            this.InvokeAsync("VoidShipment", new object[] {
                        request}, this.VoidShipmentOperationCompleted, userState);
        }
        
        private void OnVoidShipmentOperationCompleted(object arg) {
            if ((this.VoidShipmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VoidShipmentCompleted(this, new VoidShipmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://equaship.com/ImportShipments", RequestNamespace="http://equaship.com/", ResponseNamespace="http://equaship.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResponseToImportShipmentsRequest ImportShipments(ImportShipmentsRequest request) {
            object[] results = this.Invoke("ImportShipments", new object[] {
                        request});
            return ((ResponseToImportShipmentsRequest)(results[0]));
        }
        
        /// <remarks/>
        public void ImportShipmentsAsync(ImportShipmentsRequest request) {
            this.ImportShipmentsAsync(request, null);
        }
        
        /// <remarks/>
        public void ImportShipmentsAsync(ImportShipmentsRequest request, object userState) {
            if ((this.ImportShipmentsOperationCompleted == null)) {
                this.ImportShipmentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImportShipmentsOperationCompleted);
            }
            this.InvokeAsync("ImportShipments", new object[] {
                        request}, this.ImportShipmentsOperationCompleted, userState);
        }
        
        private void OnImportShipmentsOperationCompleted(object arg) {
            if ((this.ImportShipmentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ImportShipmentsCompleted(this, new ImportShipmentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://equaship.com/LocateDropOffPoints", RequestNamespace="http://equaship.com/", ResponseNamespace="http://equaship.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResponseToDropOffPointRequest LocateDropOffPoints(DropOffPointRequest request) {
            object[] results = this.Invoke("LocateDropOffPoints", new object[] {
                        request});
            return ((ResponseToDropOffPointRequest)(results[0]));
        }
        
        /// <remarks/>
        public void LocateDropOffPointsAsync(DropOffPointRequest request) {
            this.LocateDropOffPointsAsync(request, null);
        }
        
        /// <remarks/>
        public void LocateDropOffPointsAsync(DropOffPointRequest request, object userState) {
            if ((this.LocateDropOffPointsOperationCompleted == null)) {
                this.LocateDropOffPointsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLocateDropOffPointsOperationCompleted);
            }
            this.InvokeAsync("LocateDropOffPoints", new object[] {
                        request}, this.LocateDropOffPointsOperationCompleted, userState);
        }
        
        private void OnLocateDropOffPointsOperationCompleted(object arg) {
            if ((this.LocateDropOffPointsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LocateDropOffPointsCompleted(this, new LocateDropOffPointsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equaship.com/")]
    public partial class RatesAndTransitTimesRequest {
        
        private AuthenticationType authenticationField;
        
        private ShipmentType shipmentField;
        
        /// <remarks/>
        public AuthenticationType Authentication {
            get {
                return this.authenticationField;
            }
            set {
                this.authenticationField = value;
            }
        }
        
        /// <remarks/>
        public ShipmentType Shipment {
            get {
                return this.shipmentField;
            }
            set {
                this.shipmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equaship.com/")]
    public partial class AuthenticationType {
        
        private string activationKeyField;
        
        private string loginNameField;
        
        private string passwordField;
        
        /// <remarks/>
        public string ActivationKey {
            get {
                return this.activationKeyField;
            }
            set {
                this.activationKeyField = value;
            }
        }
        
        /// <remarks/>
        public string LoginName {
            get {
                return this.loginNameField;
            }
            set {
                this.loginNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equaship.com/")]
    public partial class DropOffPointType {
        
        private string dropOffIDField;
        
        private string typeField;
        
        private string nameField;
        
        private string address1Field;
        
        private string address2Field;
        
        private string cityField;
        
        private string stateField;
        
        private string zipField;
        
        private string phoneNbrField;
        
        private float longitudeField;
        
        private float lattitudeField;
        
        private string latestDropOffTimeField;
        
        private string notesField;
        
        private double distanceToOriginField;
        
        /// <remarks/>
        public string DropOffID {
            get {
                return this.dropOffIDField;
            }
            set {
                this.dropOffIDField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneNbr {
            get {
                return this.phoneNbrField;
            }
            set {
                this.phoneNbrField = value;
            }
        }
        
        /// <remarks/>
        public float Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        public float Lattitude {
            get {
                return this.lattitudeField;
            }
            set {
                this.lattitudeField = value;
            }
        }
        
        /// <remarks/>
        public string LatestDropOffTime {
            get {
                return this.latestDropOffTimeField;
            }
            set {
                this.latestDropOffTimeField = value;
            }
        }
        
        /// <remarks/>
        public string Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        public double DistanceToOrigin {
            get {
                return this.distanceToOriginField;
            }
            set {
                this.distanceToOriginField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equaship.com/")]
    public partial class DropOffPointListType {
        
        private DropOffPointType[] dropOffField;
        
        /// <remarks/>
        public DropOffPointType[] DropOff {
            get {
                return this.dropOffField;
            }
            set {
                this.dropOffField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equaship.com/")]
    public partial class ResponseToDropOffPointRequest {
        
        private ErrorType statusField;
        
        private DropOffPointListType dropOffPointsField;
        
        /// <remarks/>
        public ErrorType Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public DropOffPointListType DropOffPoints {
            get {
                return this.dropOffPointsField;
            }
            set {
                this.dropOffPointsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equaship.com/")]
    public partial class ErrorType {
        
        private int codeField;
        
        private string messageField;
        
        /// <remarks/>
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equaship.com/")]
    public partial class DropOffPointRequest {
        
        private AuthenticationType authenticationField;
        
        private string zipCodeField;
        
        /// <remarks/>
        public AuthenticationType Authentication {
            get {
                return this.authenticationField;
            }
            set {
                this.authenticationField = value;
            }
        }
        
        /// <remarks/>
        public string ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equaship.com/")]
    public partial class ResponseToImportShipmentsRequest {
        
        private ErrorType statusField;
        
        private ErrorListType errorsField;
        
        private int batchNumberField;
        
        /// <remarks/>
        public ErrorType Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public ErrorListType Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        public int BatchNumber {
            get {
                return this.batchNumberField;
            }
            set {
                this.batchNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equaship.com/")]
    public partial class ErrorListType {
        
        private ErrorType[] errorField;
        
        /// <remarks/>
        public ErrorType[] Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equaship.com/")]
    public partial class ShipmentListType {
        
        private ShipmentType[] shipmentField;
        
        /// <remarks/>
        public ShipmentType[] Shipment {
            get {
                return this.shipmentField;
            }
            set {
                this.shipmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equaship.com/")]
    public partial class ShipmentType {
        
        private AddressType returnToAddressField;
        
        private AddressType shipFromAddressField;
        
        private AddressType shipToAddressField;
        
        private string serviceCodeField;
        
        private string referenceNumberField;
        
        private string descriptionField;
        
        private string shippingNotesField;
        
        private int lengthField;
        
        private int widthField;
        
        private int heightField;
        
        private double weightField;
        
        private int packagingTypeField;
        
        private System.DateTime shipDateField;
        
        private double insuranceAmountField;
        
        private System.Nullable<InsurancePayTypeEnum> insurancePayTypeField;
        
        private double declaredValueField;
        
        private bool emailNotificationFlagField;
        
        private bool residentialFlagField;
        
        private bool saturdayDeliveryFlagField;
        
        private bool deliveryConfirmationFlagField;
        
        private bool signatureConfirmationFlagField;
        
        private bool oversize1FlagField;
        
        private bool oversize2FlagField;
        
        private int labelTypeField;
        
        private int labelSizeField;
        
        private LineItemListType lineItemsField;
        
        private PaymentInfoType paymentInfoField;
        
        /// <remarks/>
        public AddressType ReturnToAddress {
            get {
                return this.returnToAddressField;
            }
            set {
                this.returnToAddressField = value;
            }
        }
        
        /// <remarks/>
        public AddressType ShipFromAddress {
            get {
                return this.shipFromAddressField;
            }
            set {
                this.shipFromAddressField = value;
            }
        }
        
        /// <remarks/>
        public AddressType ShipToAddress {
            get {
                return this.shipToAddressField;
            }
            set {
                this.shipToAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceCode {
            get {
                return this.serviceCodeField;
            }
            set {
                this.serviceCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ReferenceNumber {
            get {
                return this.referenceNumberField;
            }
            set {
                this.referenceNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string ShippingNotes {
            get {
                return this.shippingNotesField;
            }
            set {
                this.shippingNotesField = value;
            }
        }
        
        /// <remarks/>
        public int Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        public int Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        public int Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        public double Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        public int PackagingType {
            get {
                return this.packagingTypeField;
            }
            set {
                this.packagingTypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ShipDate {
            get {
                return this.shipDateField;
            }
            set {
                this.shipDateField = value;
            }
        }
        
        /// <remarks/>
        public double InsuranceAmount {
            get {
                return this.insuranceAmountField;
            }
            set {
                this.insuranceAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<InsurancePayTypeEnum> InsurancePayType {
            get {
                return this.insurancePayTypeField;
            }
            set {
                this.insurancePayTypeField = value;
            }
        }
        
        /// <remarks/>
        public double DeclaredValue {
            get {
                return this.declaredValueField;
            }
            set {
                this.declaredValueField = value;
            }
        }
        
        /// <remarks/>
        public bool EmailNotificationFlag {
            get {
                return this.emailNotificationFlagField;
            }
            set {
                this.emailNotificationFlagField = value;
            }
        }
        
        /// <remarks/>
        public bool ResidentialFlag {
            get {
                return this.residentialFlagField;
            }
            set {
                this.residentialFlagField = value;
            }
        }
        
        /// <remarks/>
        public bool SaturdayDeliveryFlag {
            get {
                return this.saturdayDeliveryFlagField;
            }
            set {
                this.saturdayDeliveryFlagField = value;
            }
        }
        
        /// <remarks/>
        public bool DeliveryConfirmationFlag {
            get {
                return this.deliveryConfirmationFlagField;
            }
            set {
                this.deliveryConfirmationFlagField = value;
            }
        }
        
        /// <remarks/>
        public bool SignatureConfirmationFlag {
            get {
                return this.signatureConfirmationFlagField;
            }
            set {
                this.signatureConfirmationFlagField = value;
            }
        }
        
        /// <remarks/>
        public bool Oversize1Flag {
            get {
                return this.oversize1FlagField;
            }
            set {
                this.oversize1FlagField = value;
            }
        }
        
        /// <remarks/>
        public bool Oversize2Flag {
            get {
                return this.oversize2FlagField;
            }
            set {
                this.oversize2FlagField = value;
            }
        }
        
        /// <remarks/>
        public int LabelType {
            get {
                return this.labelTypeField;
            }
            set {
                this.labelTypeField = value;
            }
        }
        
        /// <remarks/>
        public int LabelSize {
            get {
                return this.labelSizeField;
            }
            set {
                this.labelSizeField = value;
            }
        }
        
        /// <remarks/>
        public LineItemListType LineItems {
            get {
                return this.lineItemsField;
            }
            set {
                this.lineItemsField = value;
            }
        }
        
        /// <remarks/>
        public PaymentInfoType PaymentInfo {
            get {
                return this.paymentInfoField;
            }
            set {
                this.paymentInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equaship.com/")]
    public partial class AddressType {
        
        private string companyField;
        
        private string departmentOrNameField;
        
        private string addressLine1Field;
        
        private string addressLine2Field;
        
        private string cityField;
        
        private string stateField;
        
        private string zipField;
        
        private string zip4Field;
        
        private string iSO2CountryCodeField;
        
        private string phoneField;
        
        private string faxField;
        
        private string emailField;
        
        /// <remarks/>
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        public string DepartmentOrName {
            get {
                return this.departmentOrNameField;
            }
            set {
                this.departmentOrNameField = value;
            }
        }
        
        /// <remarks/>
        public string AddressLine1 {
            get {
                return this.addressLine1Field;
            }
            set {
                this.addressLine1Field = value;
            }
        }
        
        /// <remarks/>
        public string AddressLine2 {
            get {
                return this.addressLine2Field;
            }
            set {
                this.addressLine2Field = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        public string Zip4 {
            get {
                return this.zip4Field;
            }
            set {
                this.zip4Field = value;
            }
        }
        
        /// <remarks/>
        public string ISO2CountryCode {
            get {
                return this.iSO2CountryCodeField;
            }
            set {
                this.iSO2CountryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equaship.com/")]
    public enum InsurancePayTypeEnum {
        
        /// <remarks/>
        EQUASURANCE,
        
        /// <remarks/>
        WAIVED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equaship.com/")]
    public partial class LineItemListType {
        
        private LineItemType[] lineItemField;
        
        /// <remarks/>
        public LineItemType[] LineItem {
            get {
                return this.lineItemField;
            }
            set {
                this.lineItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equaship.com/")]
    public partial class LineItemType {
        
        private string descriptionField;
        
        private double weightField;
        
        private double priceField;
        
        private int quantityField;
        
        private string quantityUnitField;
        
        private double unitPriceField;
        
        private string countryOfManufactureISO2Field;
        
        private string scheduleBField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public double Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        public double Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public string QuantityUnit {
            get {
                return this.quantityUnitField;
            }
            set {
                this.quantityUnitField = value;
            }
        }
        
        /// <remarks/>
        public double UnitPrice {
            get {
                return this.unitPriceField;
            }
            set {
                this.unitPriceField = value;
            }
        }
        
        /// <remarks/>
        public string CountryOfManufactureISO2 {
            get {
                return this.countryOfManufactureISO2Field;
            }
            set {
                this.countryOfManufactureISO2Field = value;
            }
        }
        
        /// <remarks/>
        public string ScheduleB {
            get {
                return this.scheduleBField;
            }
            set {
                this.scheduleBField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equaship.com/")]
    public partial class PaymentInfoType {
        
        private AddressType billingAddressField;
        
        private string cC_NumberField;
        
        private string cC_VerificationCodeField;
        
        private string cC_ExpirationMonth2CharField;
        
        private string cC_ExpirationYear2CharField;
        
        private CreditCardTypeEnum cC_TypeField;
        
        /// <remarks/>
        public AddressType BillingAddress {
            get {
                return this.billingAddressField;
            }
            set {
                this.billingAddressField = value;
            }
        }
        
        /// <remarks/>
        public string CC_Number {
            get {
                return this.cC_NumberField;
            }
            set {
                this.cC_NumberField = value;
            }
        }
        
        /// <remarks/>
        public string CC_VerificationCode {
            get {
                return this.cC_VerificationCodeField;
            }
            set {
                this.cC_VerificationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CC_ExpirationMonth2Char {
            get {
                return this.cC_ExpirationMonth2CharField;
            }
            set {
                this.cC_ExpirationMonth2CharField = value;
            }
        }
        
        /// <remarks/>
        public string CC_ExpirationYear2Char {
            get {
                return this.cC_ExpirationYear2CharField;
            }
            set {
                this.cC_ExpirationYear2CharField = value;
            }
        }
        
        /// <remarks/>
        public CreditCardTypeEnum CC_Type {
            get {
                return this.cC_TypeField;
            }
            set {
                this.cC_TypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equaship.com/")]
    public enum CreditCardTypeEnum {
        
        /// <remarks/>
        AMEX,
        
        /// <remarks/>
        VISA,
        
        /// <remarks/>
        MASTERCARD,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equaship.com/")]
    public partial class ImportShipmentsRequest {
        
        private AuthenticationType authenticationField;
        
        private ShipmentListType shipmentsField;
        
        /// <remarks/>
        public AuthenticationType Authentication {
            get {
                return this.authenticationField;
            }
            set {
                this.authenticationField = value;
            }
        }
        
        /// <remarks/>
        public ShipmentListType Shipments {
            get {
                return this.shipmentsField;
            }
            set {
                this.shipmentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equaship.com/")]
    public partial class ResponseToVoidShipmentRequest {
        
        private ErrorType statusField;
        
        /// <remarks/>
        public ErrorType Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equaship.com/")]
    public partial class VoidShipmentRequest {
        
        private AuthenticationType authenticationField;
        
        private string trackingNumberField;
        
        /// <remarks/>
        public AuthenticationType Authentication {
            get {
                return this.authenticationField;
            }
            set {
                this.authenticationField = value;
            }
        }
        
        /// <remarks/>
        public string TrackingNumber {
            get {
                return this.trackingNumberField;
            }
            set {
                this.trackingNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equaship.com/")]
    public partial class TrackingEventType {
        
        private string locationField;
        
        private string eventDescriptionField;
        
        private System.DateTime eventDateTimeField;
        
        /// <remarks/>
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public string EventDescription {
            get {
                return this.eventDescriptionField;
            }
            set {
                this.eventDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EventDateTime {
            get {
                return this.eventDateTimeField;
            }
            set {
                this.eventDateTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equaship.com/")]
    public partial class TrackingEventListType {
        
        private TrackingEventType[] eventField;
        
        /// <remarks/>
        public TrackingEventType[] Event {
            get {
                return this.eventField;
            }
            set {
                this.eventField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equaship.com/")]
    public partial class ResponseToTrackShipmentRequest {
        
        private ErrorType statusField;
        
        private TrackingEventListType eventsField;
        
        /// <remarks/>
        public ErrorType Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public TrackingEventListType Events {
            get {
                return this.eventsField;
            }
            set {
                this.eventsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equaship.com/")]
    public partial class TrackShipmentRequest {
        
        private AuthenticationType authenticationField;
        
        private string trackingNumberField;
        
        /// <remarks/>
        public AuthenticationType Authentication {
            get {
                return this.authenticationField;
            }
            set {
                this.authenticationField = value;
            }
        }
        
        /// <remarks/>
        public string TrackingNumber {
            get {
                return this.trackingNumberField;
            }
            set {
                this.trackingNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equaship.com/")]
    public partial class ShipmentDocumentType {
        
        private string documentFormatField;
        
        private string documentBase64StringField;
        
        /// <remarks/>
        public string DocumentFormat {
            get {
                return this.documentFormatField;
            }
            set {
                this.documentFormatField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentBase64String {
            get {
                return this.documentBase64StringField;
            }
            set {
                this.documentBase64StringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equaship.com/")]
    public partial class ShipmentLabelType {
        
        private int labelTypeField;
        
        private string labelBase64StringField;
        
        /// <remarks/>
        public int LabelType {
            get {
                return this.labelTypeField;
            }
            set {
                this.labelTypeField = value;
            }
        }
        
        /// <remarks/>
        public string LabelBase64String {
            get {
                return this.labelBase64StringField;
            }
            set {
                this.labelBase64StringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equaship.com/")]
    public partial class ResponseToShipmentRequest {
        
        private ErrorType statusField;
        
        private ErrorListType errorsField;
        
        private string trackingNumberField;
        
        private double totalChargesField;
        
        private ShipmentLabelType[] labelField;
        
        private ShipmentDocumentType[] documentField;
        
        /// <remarks/>
        public ErrorType Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public ErrorListType Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        public string TrackingNumber {
            get {
                return this.trackingNumberField;
            }
            set {
                this.trackingNumberField = value;
            }
        }
        
        /// <remarks/>
        public double TotalCharges {
            get {
                return this.totalChargesField;
            }
            set {
                this.totalChargesField = value;
            }
        }
        
        /// <remarks/>
        public ShipmentLabelType[] Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        public ShipmentDocumentType[] Document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equaship.com/")]
    public partial class ShipmentRequest {
        
        private AuthenticationType authenticationField;
        
        private ShipmentType shipmentField;
        
        /// <remarks/>
        public AuthenticationType Authentication {
            get {
                return this.authenticationField;
            }
            set {
                this.authenticationField = value;
            }
        }
        
        /// <remarks/>
        public ShipmentType Shipment {
            get {
                return this.shipmentField;
            }
            set {
                this.shipmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equaship.com/")]
    public partial class ServiceType {
        
        private string codeField;
        
        private string descriptionField;
        
        private double rateField;
        
        private System.DateTime estimatedDeliveryDateField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public double Rate {
            get {
                return this.rateField;
            }
            set {
                this.rateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EstimatedDeliveryDate {
            get {
                return this.estimatedDeliveryDateField;
            }
            set {
                this.estimatedDeliveryDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equaship.com/")]
    public partial class ServiceListType {
        
        private ServiceType[] serviceField;
        
        /// <remarks/>
        public ServiceType[] Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://equaship.com/")]
    public partial class ResponseToRatesAndTransitTimesRequest {
        
        private ErrorType statusField;
        
        private ServiceListType servicesField;
        
        private string notesField;
        
        /// <remarks/>
        public ErrorType Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public ServiceListType Services {
            get {
                return this.servicesField;
            }
            set {
                this.servicesField = value;
            }
        }
        
        /// <remarks/>
        public string Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetRatesAndTransitTimesCompletedEventHandler(object sender, GetRatesAndTransitTimesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRatesAndTransitTimesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRatesAndTransitTimesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseToRatesAndTransitTimesRequest Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseToRatesAndTransitTimesRequest)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ProcessShipmentCompletedEventHandler(object sender, ProcessShipmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessShipmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessShipmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseToShipmentRequest Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseToShipmentRequest)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void TrackShipmentCompletedEventHandler(object sender, TrackShipmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TrackShipmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TrackShipmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseToTrackShipmentRequest Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseToTrackShipmentRequest)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void VoidShipmentCompletedEventHandler(object sender, VoidShipmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VoidShipmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VoidShipmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseToVoidShipmentRequest Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseToVoidShipmentRequest)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ImportShipmentsCompletedEventHandler(object sender, ImportShipmentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ImportShipmentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ImportShipmentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseToImportShipmentsRequest Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseToImportShipmentsRequest)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void LocateDropOffPointsCompletedEventHandler(object sender, LocateDropOffPointsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LocateDropOffPointsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LocateDropOffPointsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseToDropOffPointRequest Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseToDropOffPointRequest)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591