///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace PerformanceTesting
{
    public partial class SetupGenericFile
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }



        public void Invoke_Action_GenericPerformance()
        {
       
        	while (!repo.BrowseForFolder.Tree1001.GenericPerformanceInfo.Exists())
           {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BrowseForFolder.Down' at Center.", repo.BrowseForFolder.DownInfo, new RecordItemIndex(70));
            repo.BrowseForFolder.Down.Click();
            Delay.Milliseconds(0);
           }
        	
        	
        }

        public void asdf()
        {
        }

    }
}