///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Create1000Orders
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("aab7191b-0fef-4208-a12f-01d219ebb4f1", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Create1000OrdersRepository repository.
        /// </summary>
        public static Create1000OrdersRepository repo = Create1000OrdersRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'MainForm.RawTextNew' at Center.", repo.MainForm.RawTextNewInfo, new RecordItemIndex(0));
            repo.MainForm.RawTextNew.MoveTo();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.RawTextNew' at Center.", repo.MainForm.RawTextNewInfo, new RecordItemIndex(1));
            repo.MainForm.RawTextNew.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddOrderWizard.RadioAssignCustomer' at Center.", repo.AddOrderWizard.RadioAssignCustomerInfo, new RecordItemIndex(2));
            repo.AddOrderWizard.RadioAssignCustomer.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'AddOrderWizard.RadioAssignCustomer' at Center.", repo.AddOrderWizard.RadioAssignCustomerInfo, new RecordItemIndex(3));
            repo.AddOrderWizard.RadioAssignCustomer.MoveTo();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddOrderWizard.Select' at Center.", repo.AddOrderWizard.SelectInfo, new RecordItemIndex(4));
            repo.AddOrderWizard.Select.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'AddOrderWizard.Select' at Center.", repo.AddOrderWizard.SelectInfo, new RecordItemIndex(5));
            repo.AddOrderWizard.Select.MoveTo();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'EntityPickerDlg.Eman' at Center.", repo.EntityPickerDlg.EmanInfo, new RecordItemIndex(6));
            repo.EntityPickerDlg.Eman.MoveTo();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EntityPickerDlg.Eman' at Center.", repo.EntityPickerDlg.EmanInfo, new RecordItemIndex(7));
            repo.EntityPickerDlg.Eman.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'EntityPickerDlg.ButtonOk' at Center.", repo.EntityPickerDlg.ButtonOkInfo, new RecordItemIndex(8));
            repo.EntityPickerDlg.ButtonOk.MoveTo();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EntityPickerDlg.ButtonOk' at Center.", repo.EntityPickerDlg.ButtonOkInfo, new RecordItemIndex(9));
            repo.EntityPickerDlg.ButtonOk.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'AddOrderWizard.Next' at Center.", repo.AddOrderWizard.NextInfo, new RecordItemIndex(10));
            repo.AddOrderWizard.Next.MoveTo();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddOrderWizard.Next' at Center.", repo.AddOrderWizard.NextInfo, new RecordItemIndex(11));
            repo.AddOrderWizard.Next.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'AddOrderWizard.Next' at Center.", repo.AddOrderWizard.NextInfo, new RecordItemIndex(12));
            repo.AddOrderWizard.Next.MoveTo();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddOrderWizard.Next' at Center.", repo.AddOrderWizard.NextInfo, new RecordItemIndex(13));
            repo.AddOrderWizard.Next.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'AddOrderWizard.Finish' at Center.", repo.AddOrderWizard.FinishInfo, new RecordItemIndex(14));
            repo.AddOrderWizard.Finish.MoveTo();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AddOrderWizard.Finish' at Center.", repo.AddOrderWizard.FinishInfo, new RecordItemIndex(15));
            repo.AddOrderWizard.Finish.Click();
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
